# ruby encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Filled Ingredients TABLE
Ingredient.create(name: "Abadèche")
Ingredient.create(name: "Abondance")
Ingredient.create(name: "Abricot")
Ingredient.create(name: "Absinthe")
Ingredient.create(name: "Achatine")
Ingredient.create(name: "Acide citrique")
Ingredient.create(name: "Acide lactique")
Ingredient.create(name: "Acide tartrique")
Ingredient.create(name: "Acidifiant")
Ingredient.create(name: "Acoupa")
Ingredient.create(name: "Adjwain")
Ingredient.create(name: "After eight")
Ingredient.create(name: "Agar-agar")
Ingredient.create(name: "Agneau")
Ingredient.create(name: "Agrume confit")
Ingredient.create(name: "Aiguillette de canard")
Ingredient.create(name: "Aiguillette de poulet")
Ingredient.create(name: "Aiguillettes de dinde")
Ingredient.create(name: "Ail")
Ingredient.create(name: "Ail semoule")
Ingredient.create(name: "Aile de poulet")
Ingredient.create(name: "Aillet")
Ingredient.create(name: "Aïoli")
Ingredient.create(name: "Airelles")
Ingredient.create(name: "Alcool de poire")
Ingredient.create(name: "Alevin")
Ingredient.create(name: "Alfafa")
Ingredient.create(name: "Algue dulse")
Ingredient.create(name: "Algue japonaise")
Ingredient.create(name: "Algue séchée")
Ingredient.create(name: "Alkermes")
Ingredient.create(name: "All bran")
Ingredient.create(name: "Alose")
Ingredient.create(name: "Alouette")
Ingredient.create(name: "Amande")
Ingredient.create(name: "Amarante")
Ingredient.create(name: "Amaretti")
Ingredient.create(name: "Amaretto")
Ingredient.create(name: "Amidon")
Ingredient.create(name: "Ananas")
Ingredient.create(name: "Anchoïade")
Ingredient.create(name: "Anchois")
Ingredient.create(name: "Andouille")
Ingredient.create(name: "Andouillette")
Ingredient.create(name: "Aneth")
Ingredient.create(name: "Angélique")
Ingredient.create(name: "Angostura")
Ingredient.create(name: "Anguille")
Ingredient.create(name: "Anis en poudre")
Ingredient.create(name: "Anis étoilé")
Ingredient.create(name: "Anis vert")
Ingredient.create(name: "Anisette")
Ingredient.create(name: "Anti-pectine")
Ingredient.create(name: "Apéricube")
Ingredient.create(name: "Apérifruit")
Ingredient.create(name: "Appenzeller")
Ingredient.create(name: "Arachide")
Ingredient.create(name: "Araignée de mer")
Ingredient.create(name: "Arbouse")
Ingredient.create(name: "Armagnac")
Ingredient.create(name: "Armoise")
Ingredient.create(name: "Aromate")
Ingredient.create(name: "Arôme")
Ingredient.create(name: "Arôme amande amère")
Ingredient.create(name: "Arôme citron")
Ingredient.create(name: "Arôme fleur d'oranger")
Ingredient.create(name: "Arôme maggi")
Ingredient.create(name: "Arôme vanille")
Ingredient.create(name: "Arquebuse")
Ingredient.create(name: "Arrow root")
Ingredient.create(name: "Artichaut")
Ingredient.create(name: "Artichaut violet")
Ingredient.create(name: "Asafoetida")
Ingredient.create(name: "Asiago")
Ingredient.create(name: "Aspartame")
Ingredient.create(name: "Asperge")
Ingredient.create(name: "Aspérule")
Ingredient.create(name: "Asti spumante")
Ingredient.create(name: "Atriau")
Ingredient.create(name: "Attiéké")
Ingredient.create(name: "Aubergine")
Ingredient.create(name: "Autruche")
Ingredient.create(name: "Avocat")
Ingredient.create(name: "Avoine")
Ingredient.create(name: "Baba")
Ingredient.create(name: "Babeurre")
Ingredient.create(name: "Babybel")
Ingredient.create(name: "Bacardi")
Ingredient.create(name: "Bacon")
Ingredient.create(name: "Badiane")
Ingredient.create(name: "Bagel")
Ingredient.create(name: "Baguette")
Ingredient.create(name: "Baie d'amélanchier")
Ingredient.create(name: "Baie de genévrier")
Ingredient.create(name: "Baie de goji")
Ingredient.create(name: "Baie de Sichuan")
Ingredient.create(name: "Baie de sureau")
Ingredient.create(name: "Baie moulu")
Ingredient.create(name: "Baie rouge")
Ingredient.create(name: "Baies d'argousier")
Ingredient.create(name: "Baies de myrte")
Ingredient.create(name: "Baies d'églantier")
Ingredient.create(name: "Baies rose")
Ingredient.create(name: "Bailey's")
Ingredient.create(name: "Bambou")
Ingredient.create(name: "Banane")
Ingredient.create(name: "Banane plantain")
Ingredient.create(name: "Banania")
Ingredient.create(name: "Banon")
Ingredient.create(name: "Banyuls")
Ingredient.create(name: "Bar")
Ingredient.create(name: "Barbe-à-papa")
Ingredient.create(name: "Barbeau")
Ingredient.create(name: "Barbue")
Ingredient.create(name: "Barde de lard")
Ingredient.create(name: "Barre bretonne marbrée")
Ingredient.create(name: "Barre chocolatée")
Ingredient.create(name: "Barre chocolatée kinder")
Ingredient.create(name: "Basilic")
Ingredient.create(name: "Basilic citron")
Ingredient.create(name: "Basilic frais")
Ingredient.create(name: "Bastogne")
Ingredient.create(name: "Batavia")
Ingredient.create(name: "Baudroie")
Ingredient.create(name: "Bavette")
Ingredient.create(name: "Beaufort")
Ingredient.create(name: "Beaujolais")
Ingredient.create(name: "Beaumes de Venise")
Ingredient.create(name: "Bécasse")
Ingredient.create(name: "Béchamel")
Ingredient.create(name: "Beef steak")
Ingredient.create(name: "Bélangère")
Ingredient.create(name: "Bénédictine")
Ingredient.create(name: "Bergamote")
Ingredient.create(name: "Bergerac")
Ingredient.create(name: "Bernique")
Ingredient.create(name: "Bètcheye")
Ingredient.create(name: "Betterave")
Ingredient.create(name: "Bettes à cardes")
Ingredient.create(name: "Beurre")
Ingredient.create(name: "Beurre allégé")
Ingredient.create(name: "Beurre d'arachide")
Ingredient.create(name: "Beurre de cacahuète")
Ingredient.create(name: "Beurre demi-sel")
Ingredient.create(name: "Beurre d'escargot")
Ingredient.create(name: "Beurre doux")
Ingredient.create(name: "Beurre tendre")
Ingredient.create(name: "Bicarbonate")
Ingredient.create(name: "Biche")
Ingredient.create(name: "Bière")
Ingredient.create(name: "Bière blonde")
Ingredient.create(name: "Bière brune")
Ingredient.create(name: "Bifteck haché")
Ingredient.create(name: "Bigarade")
Ingredient.create(name: "Bigorneau")
Ingredient.create(name: "Bille de décoration sucré")
Ingredient.create(name: "Billes multicolores")
Ingredient.create(name: "Biscotte")
Ingredient.create(name: "Biscuit")
Ingredient.create(name: "Biscuit amaretti")
Ingredient.create(name: "Biscuit anglais")
Ingredient.create(name: "Biscuit breton")
Ingredient.create(name: "Biscuit brioché")
Ingredient.create(name: "Biscuit cuiller")
Ingredient.create(name: "Biscuit rose de reims")
Ingredient.create(name: "Biscuit sablé")
Ingredient.create(name: "Biscuit salé")
Ingredient.create(name: "Biscuit sec")
Ingredient.create(name: "Biscuit thé de lu")
Ingredient.create(name: "Biscuits à la cuillère")
Ingredient.create(name: "Bison")
Ingredient.create(name: "Bitter italien")
Ingredient.create(name: "Blanc de dinde")
Ingredient.create(name: "Blanc de poulet")
Ingredient.create(name: "Blanquette de veau")
Ingredient.create(name: "Blé")
Ingredient.create(name: "Blette")
Ingredient.create(name: "Bleu")
Ingredient.create(name: "Bleu d'auvergne")
Ingredient.create(name: "Bleu de bresse")
Ingredient.create(name: "Bleu de gex")
Ingredient.create(name: "Bleu des causses")
Ingredient.create(name: "Blini")
Ingredient.create(name: "Bocconcini")
Ingredient.create(name: "Boeuf")
Ingredient.create(name: "Boeuf haché")
Ingredient.create(name: "Bois d'inde")
Ingredient.create(name: "Bois-bandé")
Ingredient.create(name: "Boisson au amande")
Ingredient.create(name: "Boisson pétillante au cola")
Ingredient.create(name: "Bok choy")
Ingredient.create(name: "Bolet")
Ingredient.create(name: "Bonbon")
Ingredient.create(name: "Bonbon arlequin")
Ingredient.create(name: "Bonbon au chocolat")
Ingredient.create(name: "Bonbons à la violette")
Ingredient.create(name: "Bonite")
Ingredient.create(name: "Bonnet")
Ingredient.create(name: "Bordeaux")
Ingredient.create(name: "Bouchée à la reine")
Ingredient.create(name: "Bouchée feuilletée")
Ingredient.create(name: "Boudin")
Ingredient.create(name: "Boudin antillais")
Ingredient.create(name: "Boudin blanc")
Ingredient.create(name: "Boudin noir")
Ingredient.create(name: "Boudoir")
Ingredient.create(name: "Bouillon")
Ingredient.create(name: "Bouillon de boeuf")
Ingredient.create(name: "Bouillon de légume")
Ingredient.create(name: "Bouillon de poule")
Ingredient.create(name: "Bouillon de volaille")
Ingredient.create(name: "Boulette de boeuf")
Ingredient.create(name: "Boulettes de viande")
Ingredient.create(name: "Boulgour")
Ingredient.create(name: "Bounty")
Ingredient.create(name: "Bouquet garni")
Ingredient.create(name: "Bourbon")
Ingredient.create(name: "Bourgeois")
Ingredient.create(name: "Bourgogne")
Ingredient.create(name: "Bourguignon")
Ingredient.create(name: "Bourrache")
Ingredient.create(name: "Boursault")
Ingredient.create(name: "Boursin")
Ingredient.create(name: "Boyau")
Ingredient.create(name: "Boyau pour saucisse")
Ingredient.create(name: "Brandade")
Ingredient.create(name: "Brandy")
Ingredient.create(name: "Brède chouchou")
Ingredient.create(name: "Brède Mafane")
Ingredient.create(name: "Bresaola")
Ingredient.create(name: "Bresse Bleu")
Ingredient.create(name: "Brick")
Ingredient.create(name: "Brie de meaux")
Ingredient.create(name: "Brillat-savarin")
Ingredient.create(name: "Brioche")
Ingredient.create(name: "Briochette")
Ingredient.create(name: "Brique")
Ingredient.create(name: "Brocciu")
Ingredient.create(name: "Brochet")
Ingredient.create(name: "Brocoli")
Ingredient.create(name: "Brousse")
Ingredient.create(name: "Broute")
Ingredient.create(name: "Brownie")
Ingredient.create(name: "Brugnon")
Ingredient.create(name: "Brunost")
Ingredient.create(name: "Bucatini")
Ingredient.create(name: "Bûche de chèvre")
Ingredient.create(name: "Bulot")
Ingredient.create(name: "Butternut")
Ingredient.create(name: "Cabécou")
Ingredient.create(name: "Cabillaud")
Ingredient.create(name: "Cacahuète grillée")
Ingredient.create(name: "Cacao")
Ingredient.create(name: "Cacao amer")
Ingredient.create(name: "Cachaça")
Ingredient.create(name: "Cachou")
Ingredient.create(name: "Caciocavallo")
Ingredient.create(name: "Cactus")
Ingredient.create(name: "Café")
Ingredient.create(name: "Café en poudre")
Ingredient.create(name: "Café instantané lyophilisé")
Ingredient.create(name: "Café soluble")
Ingredient.create(name: "Caille")
Ingredient.create(name: "Caillé de brebis")
Ingredient.create(name: "Calamar")
Ingredient.create(name: "Calisson")
Ingredient.create(name: "Caloupilé")
Ingredient.create(name: "Calvados")
Ingredient.create(name: "Cambozola")
Ingredient.create(name: "Camembert")
Ingredient.create(name: "Campari")
Ingredient.create(name: "Canard")
Ingredient.create(name: "Canard confit")
Ingredient.create(name: "Cancoillotte")
Ingredient.create(name: "Canette")
Ingredient.create(name: "Canneberge")
Ingredient.create(name: "Cannelle")
Ingredient.create(name: "Canneloni")
Ingredient.create(name: "Cantadou à l'ail et fines herbes")
Ingredient.create(name: "Cantal")
Ingredient.create(name: "Cap corse")
Ingredient.create(name: "Capellini")
Ingredient.create(name: "Cappuccino")
Ingredient.create(name: "Câpre au vinaigre")
Ingredient.create(name: "Câpres")
Ingredient.create(name: "Caprice des dieux")
Ingredient.create(name: "Capucine")
Ingredient.create(name: "Carambar")
Ingredient.create(name: "Carambole")
Ingredient.create(name: "Caramel")
Ingredient.create(name: "Caramel au beurre salé")
Ingredient.create(name: "Carbonate de calcium")
Ingredient.create(name: "Cardamome")
Ingredient.create(name: "Carde")
Ingredient.create(name: "Cardon")
Ingredient.create(name: "Carensac")
Ingredient.create(name: "Carmine")
Ingredient.create(name: "Carotte")
Ingredient.create(name: "Carpaccio")
Ingredient.create(name: "Carpe")
Ingredient.create(name: "Carré d'agneau")
Ingredient.create(name: "Carré frais")
Ingredient.create(name: "Carré gervais")
Ingredient.create(name: "Carrelet")
Ingredient.create(name: "Carvi")
Ingredient.create(name: "Casarecce")
Ingredient.create(name: "Cassis")
Ingredient.create(name: "Cassonade")
Ingredient.create(name: "Cassoulet")
Ingredient.create(name: "Cava")
Ingredient.create(name: "Caviar")
Ingredient.create(name: "Caviar d'aubergine")
Ingredient.create(name: "Cébette")
Ingredient.create(name: "Cédrat")
Ingredient.create(name: "Cédrat confit")
Ingredient.create(name: "Céleri")
Ingredient.create(name: "Céleri-rave")
Ingredient.create(name: "Cenovi")
Ingredient.create(name: "Cèpe")
Ingredient.create(name: "Céréale")
Ingredient.create(name: "Cerf")
Ingredient.create(name: "Cerfeuil")
Ingredient.create(name: "Cerise")
Ingredient.create(name: "Cerise de terre")
Ingredient.create(name: "Cerneau de noix")
Ingredient.create(name: "Cervelas")
Ingredient.create(name: "Cervelle")
Ingredient.create(name: "Chabichou")
Ingredient.create(name: "Chablis")
Ingredient.create(name: "Chair à saucisse")
Ingredient.create(name: "Chair d'alligator")
Ingredient.create(name: "Chair persillée")
Ingredient.create(name: "Chamallow")
Ingredient.create(name: "Champagne")
Ingredient.create(name: "Champignon")
Ingredient.create(name: "Champignon de Paris")
Ingredient.create(name: "Champignon frais")
Ingredient.create(name: "Champignon noir")
Ingredient.create(name: "Chanterelle")
Ingredient.create(name: "Chaource")
Ingredient.create(name: "Chapelure")
Ingredient.create(name: "Chapon")
Ingredient.create(name: "Charolais")
Ingredient.create(name: "Chartreuse jaune")
Ingredient.create(name: "Chartreuse verte")
Ingredient.create(name: "Châtaigne")
Ingredient.create(name: "Châtaigne d'eau")
Ingredient.create(name: "Chatrou")
Ingredient.create(name: "Chaume")
Ingredient.create(name: "Chavroux")
Ingredient.create(name: "Chayote")
Ingredient.create(name: "Cheddar")
Ingredient.create(name: "Chêne")
Ingredient.create(name: "Chester")
Ingredient.create(name: "Cheval")
Ingredient.create(name: "Cheveux d'ange")
Ingredient.create(name: "Chèvre")
Ingredient.create(name: "Chèvre frais")
Ingredient.create(name: "Chevreau")
Ingredient.create(name: "Chevreuil")
Ingredient.create(name: "Chicon")
Ingredient.create(name: "Chicorée")
Ingredient.create(name: "Chili")
Ingredient.create(name: "Chimère")
Ingredient.create(name: "Chipiron")
Ingredient.create(name: "Chipolata")
Ingredient.create(name: "Chips")
Ingredient.create(name: "Chips tortilla")
Ingredient.create(name: "Chips tortilla salée")
Ingredient.create(name: "Chocolat")
Ingredient.create(name: "Chocolat à tartiner")
Ingredient.create(name: "Chocolat amer")
Ingredient.create(name: "Chocolat au lait")
Ingredient.create(name: "Chocolat au riz soufflé")
Ingredient.create(name: "Chocolat aux noisettes")
Ingredient.create(name: "Chocolat blanc")
Ingredient.create(name: "Chocolat de couverture")
Ingredient.create(name: "Chocolat en poudre")
Ingredient.create(name: "Chocolat noir")
Ingredient.create(name: "Chocolat pâtissier")
Ingredient.create(name: "Chorizo")
Ingredient.create(name: "Chou")
Ingredient.create(name: "Chou chinois")
Ingredient.create(name: "Chou de bruxelles")
Ingredient.create(name: "Chou romanesco")
Ingredient.create(name: "Chouchen")
Ingredient.create(name: "Chouchou")
Ingredient.create(name: "Choucroute")
Ingredient.create(name: "Chou-fleur")
Ingredient.create(name: "Chouquette")
Ingredient.create(name: "Christophine")
Ingredient.create(name: "Chutney")
Ingredient.create(name: "Chutney au gingembre")
Ingredient.create(name: "Chutney mangue")
Ingredient.create(name: "Chutney papaye")
Ingredient.create(name: "Ciabatta")
Ingredient.create(name: "Ciboule")
Ingredient.create(name: "Ciboulette")
Ingredient.create(name: "Cidre")
Ingredient.create(name: "Cigale de mer")
Ingredient.create(name: "Cigarette croustillante")
Ingredient.create(name: "Cigarette russe")
Ingredient.create(name: "Cinq parfums")
Ingredient.create(name: "Cinq-épices")
Ingredient.create(name: "Cinzano")
Ingredient.create(name: "Citron")
Ingredient.create(name: "Citron confit")
Ingredient.create(name: "Citron vert")
Ingredient.create(name: "Citronat")
Ingredient.create(name: "Citronnelle")
Ingredient.create(name: "Citrouille")
Ingredient.create(name: "Cive")
Ingredient.create(name: "Clairette de Die")
Ingredient.create(name: "Clams")
Ingredient.create(name: "Clémentine")
Ingredient.create(name: "Clou de girofle")
Ingredient.create(name: "Clovisse")
Ingredient.create(name: "Coca")
Ingredient.create(name: "Cochon")
Ingredient.create(name: "Coco de paimpol")
Ingredient.create(name: "Coco en poudre")
Ingredient.create(name: "Coco plat")
Ingredient.create(name: "Coeur")
Ingredient.create(name: "Coeur d'artichaut")
Ingredient.create(name: "Coeur de palmier")
Ingredient.create(name: "Coeur en sucre")
Ingredient.create(name: "Cognac")
Ingredient.create(name: "Cognac Fine Champagne")
Ingredient.create(name: "Coing")
Ingredient.create(name: "Cointreau")
Ingredient.create(name: "Coleslaw")
Ingredient.create(name: "Colin")
Ingredient.create(name: "Collet fumé")
Ingredient.create(name: "Collier d'agneau")
Ingredient.create(name: "Collier de boeuf")
Ingredient.create(name: "Colorant")
Ingredient.create(name: "Colorant alimentaire")
Ingredient.create(name: "Combava")
Ingredient.create(name: "Compote")
Ingredient.create(name: "Comté")
Ingredient.create(name: "Concentré de coco")
Ingredient.create(name: "Concentré de tomate")
Ingredient.create(name: "Concentré pour soupe chinoise")
Ingredient.create(name: "Conchiglione")
Ingredient.create(name: "Concombre")
Ingredient.create(name: "Confisuc")
Ingredient.create(name: "Confit de canard")
Ingredient.create(name: "Confit de courgettes")
Ingredient.create(name: "Confit d'oignon")
Ingredient.create(name: "Confiture")
Ingredient.create(name: "Confiture d'abricot")
Ingredient.create(name: "Confiture de cerise")
Ingredient.create(name: "Confiture de fruit rouge")
Ingredient.create(name: "Confiture de groseille")
Ingredient.create(name: "Confiture de lait")
Ingredient.create(name: "Confiture de mangue")
Ingredient.create(name: "Confiture de poire")
Ingredient.create(name: "Congre")
Ingredient.create(name: "Consommé de gibier")
Ingredient.create(name: "Contre-filet")
Ingredient.create(name: "Cookie")
Ingredient.create(name: "Cookie chocolat")
Ingredient.create(name: "Copeau de chocolat blanc")
Ingredient.create(name: "Coppa")
Ingredient.create(name: "Coq")
Ingredient.create(name: "Coque")
Ingredient.create(name: "Coquelet")
Ingredient.create(name: "Coquelicot")
Ingredient.create(name: "Coquille saint-jacques")
Ingredient.create(name: "Coquillettes")
Ingredient.create(name: "Coriandre")
Ingredient.create(name: "Coriandre en grains")
Ingredient.create(name: "Corn flakes")
Ingredient.create(name: "Corned beef")
Ingredient.create(name: "Cornet")
Ingredient.create(name: "Cornet de glace")
Ingredient.create(name: "Cornette")
Ingredient.create(name: "Cornichon au vinaigre")
Ingredient.create(name: "Cornichons")
Ingredient.create(name: "Corossol")
Ingredient.create(name: "Côte de boeuf")
Ingredient.create(name: "Côtelettes d'agneau")
Ingredient.create(name: "Côtes d'agneau")
Ingredient.create(name: "Côtes de porc")
Ingredient.create(name: "Cottage cheese")
Ingredient.create(name: "Couche")
Ingredient.create(name: "Coude")
Ingredient.create(name: "Couenne")
Ingredient.create(name: "Couenne de panne")
Ingredient.create(name: "Coulemelle")
Ingredient.create(name: "Coulis")
Ingredient.create(name: "Coulis d'abricot")
Ingredient.create(name: "Coulis de fruit rouge")
Ingredient.create(name: "Coulis de tomate")
Ingredient.create(name: "Coulommier")
Ingredient.create(name: "Courge")
Ingredient.create(name: "Courge musquée")
Ingredient.create(name: "Courge spaghetti")
Ingredient.create(name: "Courgette")
Ingredient.create(name: "Court bouillon de volaille")
Ingredient.create(name: "Court-bouillon")
Ingredient.create(name: "Couscous")
Ingredient.create(name: "Couteau")
Ingredient.create(name: "Crabe")
Ingredient.create(name: "Cracker")
Ingredient.create(name: "Cranberrie")
Ingredient.create(name: "Cream cheese")
Ingredient.create(name: "Crema mandorla")
Ingredient.create(name: "Crémant")
Ingredient.create(name: "Crème")
Ingredient.create(name: "Crème allégée")
Ingredient.create(name: "Crème anglaise")
Ingredient.create(name: "Crème balsamique")
Ingredient.create(name: "Crème chantilly")
Ingredient.create(name: "Crème d'anchoi")
Ingredient.create(name: "Crème de marron")
Ingredient.create(name: "Crème de mûre")
Ingredient.create(name: "Crème de soja")
Ingredient.create(name: "Crème dessert à la vanille")
Ingredient.create(name: "Crème dessert au chocolat")
Ingredient.create(name: "Crème épaisse")
Ingredient.create(name: "Crème fleurette")
Ingredient.create(name: "Crème fouettée")
Ingredient.create(name: "Crême fraîche")
Ingredient.create(name: "Crème fraîche allégée")
Ingredient.create(name: "Crème fraîche épaisse")
Ingredient.create(name: "Crème fraîche liquide")
Ingredient.create(name: "Crème liquide")
Ingredient.create(name: "Crème pâtissière")
Ingredient.create(name: "Crème semi-épaisse")
Ingredient.create(name: "Crêpe")
Ingredient.create(name: "Crêpe dentelle")
Ingredient.create(name: "Crépidule")
Ingredient.create(name: "Crépine")
Ingredient.create(name: "Crépinette")
Ingredient.create(name: "Cresson")
Ingredient.create(name: "Cressonnette")
Ingredient.create(name: "Crevette")
Ingredient.create(name: "Crevette bouquet")
Ingredient.create(name: "Crevette rose")
Ingredient.create(name: "Crevette tigrée")
Ingredient.create(name: "Crevettes grises")
Ingredient.create(name: "Croissant")
Ingredient.create(name: "Croquants de Cordes")
Ingredient.create(name: "Crosne")
Ingredient.create(name: "Crottin de chèvre")
Ingredient.create(name: "Crottins de chavignol")
Ingredient.create(name: "Croûton à l'ail et au fine herbe à l'ancienne")
Ingredient.create(name: "Croûtons")
Ingredient.create(name: "Crozet")
Ingredient.create(name: "Crunch")
Ingredient.create(name: "Cuajada")
Ingredient.create(name: "Cube de bouillon")
Ingredient.create(name: "Cube Maggi")
Ingredient.create(name: "Cube pot au feu")
Ingredient.create(name: "Cuberdon")
Ingredient.create(name: "Cuisse de canard")
Ingredient.create(name: "Cuisse de dinde")
Ingredient.create(name: "Cuisse de grenouille")
Ingredient.create(name: "Cuisse de poulet")
Ingredient.create(name: "Cuisses de lapin")
Ingredient.create(name: "Cumin")
Ingredient.create(name: "Cumin en poudre")
Ingredient.create(name: "Curaçao")
Ingredient.create(name: "Curcuma")
Ingredient.create(name: "Curé nantais")
Ingredient.create(name: "Curry")
Ingredient.create(name: "Cynorhodon")
Ingredient.create(name: "Daim")
Ingredient.create(name: "Dakatine")
Ingredient.create(name: "Danette")
Ingredient.create(name: "Dashi")
Ingredient.create(name: "Datte")
Ingredient.create(name: "Daucus de Crête")
Ingredient.create(name: "Daurade")
Ingredient.create(name: "Décor en sucre")
Ingredient.create(name: "Dés de jambon")
Ingredient.create(name: "Dinde")
Ingredient.create(name: "Dindonneau")
Ingredient.create(name: "Diot")
Ingredient.create(name: "Djansan")
Ingredient.create(name: "Dorade")
Ingredient.create(name: "Doré")
Ingredient.create(name: "Doubanjiang")
Ingredient.create(name: "Double concentré de tomate")
Ingredient.create(name: "Dragée")
Ingredient.create(name: "Dragibus")
Ingredient.create(name: "Eau")
Ingredient.create(name: "Eau de fleur d'oranger")
Ingredient.create(name: "Eau gazeuse")
Ingredient.create(name: "Échalote")
Ingredient.create(name: "Échine de porc")
Ingredient.create(name: "Écorce d'orange")
Ingredient.create(name: "Écorces d'oranges confites")
Ingredient.create(name: "Écrevisse")
Ingredient.create(name: "Edam")
Ingredient.create(name: "Édulcorant")
Ingredient.create(name: "Églantine")
Ingredient.create(name: "Églefin")
Ingredient.create(name: "Elbot fumé")
Ingredient.create(name: "Emmental")
Ingredient.create(name: "Empereur")
Ingredient.create(name: "Encornet")
Ingredient.create(name: "Endive")
Ingredient.create(name: "Entrecôte")
Ingredient.create(name: "Épaule")
Ingredient.create(name: "Épaule d'agneau")
Ingredient.create(name: "Épaule de biche")
Ingredient.create(name: "Épeautre")
Ingredient.create(name: "Épice")
Ingredient.create(name: "Épice à colombo")
Ingredient.create(name: "Épice à couscous")
Ingredient.create(name: "Épice à paella")
Ingredient.create(name: "Épice à pain d'épice")
Ingredient.create(name: "Épice à vin chaud")
Ingredient.create(name: "Épice à volaille")
Ingredient.create(name: "Épice cajun")
Ingredient.create(name: "Épice espagnole")
Ingredient.create(name: "Épice indienne")
Ingredient.create(name: "Épice marocaine")
Ingredient.create(name: "Épice pour pizza")
Ingredient.create(name: "Épice pour poisson")
Ingredient.create(name: "Épice pour tajine")
Ingredient.create(name: "Épice tandoori")
Ingredient.create(name: "Épinard")
Ingredient.create(name: "Épinard frais")
Ingredient.create(name: "Épine vinette")
Ingredient.create(name: "Époisse")
Ingredient.create(name: "Érable")
Ingredient.create(name: "Escalope")
Ingredient.create(name: "Escalope de dinde")
Ingredient.create(name: "Escalope de porc")
Ingredient.create(name: "Escalope de poulet")
Ingredient.create(name: "Escargot")
Ingredient.create(name: "Espadon")
Ingredient.create(name: "Essence d'amande amère")
Ingredient.create(name: "Estomac")
Ingredient.create(name: "Estragon")
Ingredient.create(name: "Esturgeon")
Ingredient.create(name: "Etorki")
Ingredient.create(name: "Étrilles")
Ingredient.create(name: "Expresso")
Ingredient.create(name: "Extrait d'amande")
Ingredient.create(name: "Extrait d'amande amère")
Ingredient.create(name: "Extrait de café")
Ingredient.create(name: "Extrait de coco")
Ingredient.create(name: "Extrait de vanille")
Ingredient.create(name: "Extrait de vanille liquide")
Ingredient.create(name: "Faisan")
Ingredient.create(name: "Faisselle")
Ingredient.create(name: "Fajitas")
Ingredient.create(name: "Fanta")
Ingredient.create(name: "Farce")
Ingredient.create(name: "Farfalle")
Ingredient.create(name: "Farine")
Ingredient.create(name: "Farine de blé")
Ingredient.create(name: "Farine de blé noir")
Ingredient.create(name: "Farine de chataîgne")
Ingredient.create(name: "Farine de maïs")
Ingredient.create(name: "Farine de sarrasin")
Ingredient.create(name: "Farine de tapioca")
Ingredient.create(name: "Farine fermentante")
Ingredient.create(name: "Farine sans gluten")
Ingredient.create(name: "Faux-filet")
Ingredient.create(name: "Fécule")
Ingredient.create(name: "Fécule de maïs")
Ingredient.create(name: "Fécule de pomme de terre")
Ingredient.create(name: "Fenouil")
Ingredient.create(name: "Fenugreek")
Ingredient.create(name: "Ferment lactique")
Ingredient.create(name: "Feta")
Ingredient.create(name: "Feta marinée")
Ingredient.create(name: "Fettucine")
Ingredient.create(name: "Feuille de bananier")
Ingredient.create(name: "Feuille de brick")
Ingredient.create(name: "Feuille de cari")
Ingredient.create(name: "Feuille de cerisier")
Ingredient.create(name: "Feuille de citronnelle")
Ingredient.create(name: "Feuille de citronnier")
Ingredient.create(name: "Feuille de combava")
Ingredient.create(name: "Feuille de coriandre")
Ingredient.create(name: "Feuille de curry")
Ingredient.create(name: "Feuille de figuier")
Ingredient.create(name: "Feuille de guigne")
Ingredient.create(name: "Feuille de jasmin")
Ingredient.create(name: "Feuille de laurier")
Ingredient.create(name: "Feuille de marjolaine")
Ingredient.create(name: "Feuille de menthe")
Ingredient.create(name: "Feuille de nori")
Ingredient.create(name: "Feuille de riz")
Ingredient.create(name: "Feuille de salam")
Ingredient.create(name: "Feuille de shiso")
Ingredient.create(name: "Feuille de Tito")
Ingredient.create(name: "Feuille de vigne")
Ingredient.create(name: "Feuille de won-ton")
Ingredient.create(name: "Feuilles de guascas")
Ingredient.create(name: "Feuilles de noyer")
Ingredient.create(name: "Feuilles de pêcher")
Ingredient.create(name: "Feuillet")
Ingredient.create(name: "Feuilleté")
Ingredient.create(name: "Feuillets à raviolis")
Ingredient.create(name: "Fève")
Ingredient.create(name: "Févette")
Ingredient.create(name: "Ficelle")
Ingredient.create(name: "Figatelli")
Ingredient.create(name: "Figolus")
Ingredient.create(name: "Figue")
Ingredient.create(name: "Figue de barbarie")
Ingredient.create(name: "Filet d'agneau")
Ingredient.create(name: "Filet de boeuf")
Ingredient.create(name: "Filet de poulet")
Ingredient.create(name: "Filet mignon")
Ingredient.create(name: "Filo")
Ingredient.create(name: "Fixe chantilly")
Ingredient.create(name: "Flageolet")
Ingredient.create(name: "Flanchet")
Ingredient.create(name: "Flétan")
Ingredient.create(name: "Fleur d'acacia")
Ingredient.create(name: "Fleur de camomille")
Ingredient.create(name: "Fleur de jasmin")
Ingredient.create(name: "Fleur de sel")
Ingredient.create(name: "Fleur de sureau")
Ingredient.create(name: "Fleur d'hibiscus")
Ingredient.create(name: "Fleur d'oranger")
Ingredient.create(name: "Fleuron feuilleté")
Ingredient.create(name: "Fleurs de lilas")
Ingredient.create(name: "Flocon d'avoine")
Ingredient.create(name: "Flocon de purée")
Ingredient.create(name: "Floraline")
Ingredient.create(name: "Florentin")
Ingredient.create(name: "Fluff")
Ingredient.create(name: "Flûte")
Ingredient.create(name: "Foie")
Ingredient.create(name: "Foie gras")
Ingredient.create(name: "Fond d'artichaut")
Ingredient.create(name: "Fond de rôti")
Ingredient.create(name: "Fond de veau")
Ingredient.create(name: "Fond de volaille")
Ingredient.create(name: "Fondant")
Ingredient.create(name: "Fonds")
Ingredient.create(name: "Fonio")
Ingredient.create(name: "Fourme d'ambert")
Ingredient.create(name: "Fourme de montbrison")
Ingredient.create(name: "Fraise")
Ingredient.create(name: "Fraise des bois")
Ingredient.create(name: "Fraise gariguette")
Ingredient.create(name: "Fraise tagada")
Ingredient.create(name: "Framboise")
Ingredient.create(name: "Frangipane")
Ingredient.create(name: "Frisée")
Ingredient.create(name: "Frite")
Ingredient.create(name: "Fromage à raclette")
Ingredient.create(name: "Fromage ail et fines herbes")
Ingredient.create(name: "Fromage blanc")
Ingredient.create(name: "Fromage blanc sucré")
Ingredient.create(name: "Fromage de chèvre")
Ingredient.create(name: "Fromage frais")
Ingredient.create(name: "Fromage râpé")
Ingredient.create(name: "Fructose")
Ingredient.create(name: "Fruit")
Ingredient.create(name: "Fruit à pain")
Ingredient.create(name: "Fruit confit")
Ingredient.create(name: "Fruit de la passion")
Ingredient.create(name: "Fruit de mer")
Ingredient.create(name: "Fruit exotique")
Ingredient.create(name: "Fruit rouge")
Ingredient.create(name: "Fruit sec")
Ingredient.create(name: "Fumet")
Ingredient.create(name: "Fumet de crustacé")
Ingredient.create(name: "Fusilli")
Ingredient.create(name: "Galanga")
Ingredient.create(name: "Galette")
Ingredient.create(name: "Galette de blé")
Ingredient.create(name: "Galettes (bretonnes)")
Ingredient.create(name: "Galettes de riz")
Ingredient.create(name: "Gambas")
Ingredient.create(name: "Ganache au chocolat")
Ingredient.create(name: "Gaperon")
Ingredient.create(name: "Garam massala")
Ingredient.create(name: "Gari")
Ingredient.create(name: "Gâteaux")
Ingredient.create(name: "Gaufre")
Ingredient.create(name: "Gaufrette")
Ingredient.create(name: "Gavotte")
Ingredient.create(name: "Gélatine")
Ingredient.create(name: "Gélatine en feuilles")
Ingredient.create(name: "Gélatine en poudre")
Ingredient.create(name: "Gelée")
Ingredient.create(name: "Gelée anglaise à la fraise")
Ingredient.create(name: "Gelée au madère")
Ingredient.create(name: "Gelée au vin blanc")
Ingredient.create(name: "Gelée d'abricot")
Ingredient.create(name: "Gelsuc")
Ingredient.create(name: "Gendarme")
Ingredient.create(name: "Génépi")
Ingredient.create(name: "Genièvre")
Ingredient.create(name: "Génoise")
Ingredient.create(name: "Germe de luzerne")
Ingredient.create(name: "Germes de soja")
Ingredient.create(name: "Gervita")
Ingredient.create(name: "Gésier de volaille")
Ingredient.create(name: "Gésiers")
Ingredient.create(name: "Get 27")
Ingredient.create(name: "Gewurztraminer")
Ingredient.create(name: "Ghee")
Ingredient.create(name: "Gianduja")
Ingredient.create(name: "Gigérine")
Ingredient.create(name: "Gigot d'agneau")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Gingembre")
Ingredient.create(name: "Gingembre confit")
Ingredient.create(name: "Ginger Ale")
Ingredient.create(name: "Gini")
Ingredient.create(name: "Giraumon")
Ingredient.create(name: "Girelle")
Ingredient.create(name: "Girofle")
Ingredient.create(name: "Girolle")
Ingredient.create(name: "Giromon")
Ingredient.create(name: "Gîte")
Ingredient.create(name: "Glaçage")
Ingredient.create(name: "Glace")
Ingredient.create(name: "Glace à la noix de coco")
Ingredient.create(name: "Glace à la passion")
Ingredient.create(name: "Glace à la poire")
Ingredient.create(name: "Glace au chocolat")
Ingredient.create(name: "Glace au noix de pécan")
Ingredient.create(name: "Glace au nougat")
Ingredient.create(name: "Glace au rhum")
Ingredient.create(name: "Glace au spéculoos")
Ingredient.create(name: "Glace caramel au beurre salé")
Ingredient.create(name: "Glace coco")
Ingredient.create(name: "Glace fraise")
Ingredient.create(name: "Glace framboise")
Ingredient.create(name: "Glace pilée")
Ingredient.create(name: "Glace stracciatella")
Ingredient.create(name: "Glace vanille")
Ingredient.create(name: "Glaçon")
Ingredient.create(name: "Glucose")
Ingredient.create(name: "Glucose liquide")
Ingredient.create(name: "Glutamate")
Ingredient.create(name: "Glycérine alimentaire")
Ingredient.create(name: "Gnocchi")
Ingredient.create(name: "Gofio")
Ingredient.create(name: "Golden sirup")
Ingredient.create(name: "Golmotte")
Ingredient.create(name: "Gomasio")
Ingredient.create(name: "Gombo")
Ingredient.create(name: "Gomme arabique")
Ingredient.create(name: "Gomme de guar")
Ingredient.create(name: "Gomme de xanthane")
Ingredient.create(name: "Gorgonzola")
Ingredient.create(name: "Gouda")
Ingredient.create(name: "Goyave")
Ingredient.create(name: "Goyavier")
Ingredient.create(name: "Grain de genévrier")
Ingredient.create(name: "Grain de palme")
Ingredient.create(name: "Graine d'anis")
Ingredient.create(name: "Graine d'anis vert")
Ingredient.create(name: "Graine de coriandre")
Ingredient.create(name: "Graine de courge")
Ingredient.create(name: "Graine de fenouil")
Ingredient.create(name: "Graine de lin")
Ingredient.create(name: "Graine germée")
Ingredient.create(name: "Graines de lupin")
Ingredient.create(name: "Graines de nigelle")
Ingredient.create(name: "Graines de tournesol")
Ingredient.create(name: "Graisse à friteuse")
Ingredient.create(name: "Graisse de coco")
Ingredient.create(name: "Graisse de coprah")
Ingredient.create(name: "Graisse de palme")
Ingredient.create(name: "Graisse d'oie")
Ingredient.create(name: "Graisse végétale")
Ingredient.create(name: "Grana padano")
Ingredient.create(name: "Grand-marnier")
Ingredient.create(name: "Granny smith")
Ingredient.create(name: "Granulés multicolores")
Ingredient.create(name: "Grappa")
Ingredient.create(name: "Gras double")
Ingredient.create(name: "Grenade")
Ingredient.create(name: "Grenadier")
Ingredient.create(name: "Grenadin")
Ingredient.create(name: "Grenadine")
Ingredient.create(name: "Grenaille")
Ingredient.create(name: "Gressin")
Ingredient.create(name: "Greubon")
Ingredient.create(name: "Griotte")
Ingredient.create(name: "Grive")
Ingredient.create(name: "Grondin")
Ingredient.create(name: "Gros sel")
Ingredient.create(name: "Groseille")
Ingredient.create(name: "Groseille à maquereaux")
Ingredient.create(name: "Gruau")
Ingredient.create(name: "Gruyère")
Ingredient.create(name: "Gruyère râpé")
Ingredient.create(name: "Guacamole")
Ingredient.create(name: "Guigne")
Ingredient.create(name: "Guignolet")
Ingredient.create(name: "Guimauve")
Ingredient.create(name: "Guinness")
Ingredient.create(name: "Haddock")
Ingredient.create(name: "Hampe")
Ingredient.create(name: "Hareng")
Ingredient.create(name: "Haricot")
Ingredient.create(name: "Haricot azuki")
Ingredient.create(name: "Haricot beurre")
Ingredient.create(name: "Haricot blanc")
Ingredient.create(name: "Haricot coco")
Ingredient.create(name: "Haricot de soissons")
Ingredient.create(name: "Haricot lingot")
Ingredient.create(name: "Haricot mange-tout")
Ingredient.create(name: "Haricot mungo")
Ingredient.create(name: "Haricot noir")
Ingredient.create(name: "Haricot pinto")
Ingredient.create(name: "Haricot plat")
Ingredient.create(name: "Haricot rouge")
Ingredient.create(name: "Haricot sec")
Ingredient.create(name: "Haricot tarbais")
Ingredient.create(name: "Haricot vert")
Ingredient.create(name: "Harissa")
Ingredient.create(name: "Herbe")
Ingredient.create(name: "Herbe aromatique")
Ingredient.create(name: "Herbes de provence")
Ingredient.create(name: "Homard")
Ingredient.create(name: "Hostie")
Ingredient.create(name: "Houblon")
Ingredient.create(name: "Houmous")
Ingredient.create(name: "Huile")
Ingredient.create(name: "Huile d'arachide")
Ingredient.create(name: "Huile d'argan")
Ingredient.create(name: "Huile de coco")
Ingredient.create(name: "Huile de colza")
Ingredient.create(name: "Huile de friture")
Ingredient.create(name: "Huile de noisette")
Ingredient.create(name: "Huile de noix")
Ingredient.create(name: "Huile de palme")
Ingredient.create(name: "Huile de pépin de raisin")
Ingredient.create(name: "Huile de sésame")
Ingredient.create(name: "Huile de tournesol")
Ingredient.create(name: "Huile de truffe")
Ingredient.create(name: "Huile d'olive")
Ingredient.create(name: "Huile parfumée au basilic")
Ingredient.create(name: "Huître")
Ingredient.create(name: "Hydromel")
Ingredient.create(name: "Hypocra")
Ingredient.create(name: "Igname")
Ingredient.create(name: "Irish mist")
Ingredient.create(name: "Jalapeno")
Ingredient.create(name: "Jambon")
Ingredient.create(name: "Jambon blanc")
Ingredient.create(name: "Jambon de bayonne")
Ingredient.create(name: "Jambon de parme")
Ingredient.create(name: "Jambon de vendée")
Ingredient.create(name: "Jambon de virginie")
Ingredient.create(name: "Jambon fumé")
Ingredient.create(name: "Jambon ibérique")
Ingredient.create(name: "Jambon persillé")
Ingredient.create(name: "Jambon sec")
Ingredient.create(name: "Jambonneau")
Ingredient.create(name: "Jarret de boeuf")
Ingredient.create(name: "Jarret de veau")
Ingredient.create(name: "Jésus")
Ingredient.create(name: "Joue")
Ingredient.create(name: "Joue de lotte")
Ingredient.create(name: "Joue de porc")
Ingredient.create(name: "Julienne")
Ingredient.create(name: "Jumbo")
Ingredient.create(name: "Jus d'abricot")
Ingredient.create(name: "Jus d'agrumes")
Ingredient.create(name: "Jus d'ananas")
Ingredient.create(name: "Jus de banane")
Ingredient.create(name: "Jus de citron")
Ingredient.create(name: "Jus de cranberries")
Ingredient.create(name: "Jus de cuisson")
Ingredient.create(name: "Jus de fruit de la passion")
Ingredient.create(name: "Jus de fruit multivitaminé")
Ingredient.create(name: "Jus de fruit rouge")
Ingredient.create(name: "Jus de mirabelle")
Ingredient.create(name: "Jus de rôti")
Ingredient.create(name: "Jus d'orange")
Ingredient.create(name: "Jus exotique")
Ingredient.create(name: "Kaki")
Ingredient.create(name: "Kale")
Ingredient.create(name: "Kangourou")
Ingredient.create(name: "Kari gosse")
Ingredient.create(name: "Kasha")
Ingredient.create(name: "Kefalotiri")
Ingredient.create(name: "Kéfir")
Ingredient.create(name: "Ketchup")
Ingredient.create(name: "Kinder surprise")
Ingredient.create(name: "Kiri")
Ingredient.create(name: "Kirsch")
Ingredient.create(name: "Kiwi")
Ingredient.create(name: "Knack")
Ingredient.create(name: "Knacki")
Ingredient.create(name: "Knacki ball")
Ingredient.create(name: "Kombu")
Ingredient.create(name: "Kororima")
Ingredient.create(name: "Krisproll")
Ingredient.create(name: "Kub or")
Ingredient.create(name: "Kumquat")
Ingredient.create(name: "Lactaire délicieux")
Ingredient.create(name: "Lait")
Ingredient.create(name: "Lait concentré")
Ingredient.create(name: "Lait concentré non sucré")
Ingredient.create(name: "Lait concentré sucré")
Ingredient.create(name: "Lait de chèvre")
Ingredient.create(name: "Lait de coco")
Ingredient.create(name: "Lait de soja")
Ingredient.create(name: "Lait demi-écrémé")
Ingredient.create(name: "Lait demi-écrémé concentré")
Ingredient.create(name: "Lait écrémé")
Ingredient.create(name: "Lait en poudre")
Ingredient.create(name: "Lait en poudre demi-écrémé")
Ingredient.create(name: "Lait en poudre écrémé")
Ingredient.create(name: "Lait en poudre entier")
Ingredient.create(name: "Lait entier")
Ingredient.create(name: "Lait entier concentré")
Ingredient.create(name: "Lait fermenté")
Ingredient.create(name: "Lait maternisé")
Ingredient.create(name: "Laitue")
Ingredient.create(name: "Lambig")
Ingredient.create(name: "Lambis")
Ingredient.create(name: "Lamproie")
Ingredient.create(name: "Langouste")
Ingredient.create(name: "Langoustine")
Ingredient.create(name: "Langres")
Ingredient.create(name: "Langue")
Ingredient.create(name: "Langue de chat")
Ingredient.create(name: "Langue de mouton")
Ingredient.create(name: "Lapin")
Ingredient.create(name: "Lapin entier")
Ingredient.create(name: "Lard")
Ingredient.create(name: "Lard fumé")
Ingredient.create(name: "Lardons")
Ingredient.create(name: "Lardons fumés")
Ingredient.create(name: "Lasagnes")
Ingredient.create(name: "Laurier")
Ingredient.create(name: "Lavande")
Ingredient.create(name: "Leerdammer")
Ingredient.create(name: "Leffe")
Ingredient.create(name: "Lemon curd")
Ingredient.create(name: "Lemon-grass")
Ingredient.create(name: "Lentille")
Ingredient.create(name: "Lentille corail")
Ingredient.create(name: "Lentille verte")
Ingredient.create(name: "Lentin")
Ingredient.create(name: "Levain")
Ingredient.create(name: "Levure")
Ingredient.create(name: "Levure chimique")
Ingredient.create(name: "Levure de boulanger")
Ingredient.create(name: "Levure de boulanger fraîche")
Ingredient.create(name: "Levure de boulanger sèche")
Ingredient.create(name: "Liant")
Ingredient.create(name: "Liant instantané")
Ingredient.create(name: "Lieu jaune")
Ingredient.create(name: "Lieu noir")
Ingredient.create(name: "Lièvre")
Ingredient.create(name: "Lillet blanc")
Ingredient.create(name: "Limande")
Ingredient.create(name: "Lime")
Ingredient.create(name: "Limonade")
Ingredient.create(name: "Limoncello")
Ingredient.create(name: "Lingue")
Ingredient.create(name: "Linguine")
Ingredient.create(name: "Liqueur")
Ingredient.create(name: "Liqueur d'amande")
Ingredient.create(name: "Liqueur d'anis")
Ingredient.create(name: "Liqueur de litchi")
Ingredient.create(name: "Liqueur de menthe")
Ingredient.create(name: "Liqueur de pomme")
Ingredient.create(name: "Liqueur d'orange")
Ingredient.create(name: "Liseron d'eau")
Ingredient.create(name: "Litchi")
Ingredient.create(name: "Litchi au sirop")
Ingredient.create(name: "Livarot")
Ingredient.create(name: "Livèche")
Ingredient.create(name: "Longanisse")
Ingredient.create(name: "Lotte")
Ingredient.create(name: "Lotus")
Ingredient.create(name: "Lou pérac")
Ingredient.create(name: "Loup")
Ingredient.create(name: "Loup de mer")
Ingredient.create(name: "Lupini")
Ingredient.create(name: "M&M's cacahuète")
Ingredient.create(name: "Maasdam")
Ingredient.create(name: "Macaron")
Ingredient.create(name: "Macaroni")
Ingredient.create(name: "Macédoine")
Ingredient.create(name: "Mâche")
Ingredient.create(name: "Macis")
Ingredient.create(name: "Macreuse")
Ingredient.create(name: "Madeleine")
Ingredient.create(name: "Madère")
Ingredient.create(name: "Magret de canard")
Ingredient.create(name: "Magret de canard fumé")
Ingredient.create(name: "Magret de canard séché")
Ingredient.create(name: "Magret fumé")
Ingredient.create(name: "Magret séché")
Ingredient.create(name: "Mahi mahi")
Ingredient.create(name: "Maïs")
Ingredient.create(name: "Maïzena")
Ingredient.create(name: "Malibu")
Ingredient.create(name: "Malibu coco")
Ingredient.create(name: "Manchego")
Ingredient.create(name: "Mandarine")
Ingredient.create(name: "Mangoustan")
Ingredient.create(name: "Mangue")
Ingredient.create(name: "Maniguette")
Ingredient.create(name: "Manioc")
Ingredient.create(name: "Manouri")
Ingredient.create(name: "Manzana")
Ingredient.create(name: "Maquereau")
Ingredient.create(name: "Marasquin")
Ingredient.create(name: "Marc")
Ingredient.create(name: "Marcassin")
Ingredient.create(name: "Margarine")
Ingredient.create(name: "Marie brizard")
Ingredient.create(name: "Marjolaine")
Ingredient.create(name: "Marlin")
Ingredient.create(name: "Marmelade d'abricot")
Ingredient.create(name: "Marmelade d'orange")
Ingredient.create(name: "Maroilles")
Ingredient.create(name: "MaronSui's")
Ingredient.create(name: "Marrons")
Ingredient.create(name: "Mars")
Ingredient.create(name: "Marsala")
Ingredient.create(name: "Martini")
Ingredient.create(name: "Martini blanc")
Ingredient.create(name: "Martini Rosso")
Ingredient.create(name: "Mascarpone")
Ingredient.create(name: "Massala")
Ingredient.create(name: "Massalé")
Ingredient.create(name: "Massepain")
Ingredient.create(name: "Mastelle")
Ingredient.create(name: "Matière grasse")
Ingredient.create(name: "Maton")
Ingredient.create(name: "Maury")
Ingredient.create(name: "Mayonnaise")
Ingredient.create(name: "Mayonnaise au citron")
Ingredient.create(name: "Mélange 4 épices")
Ingredient.create(name: "Mélange 4 parfums")
Ingredient.create(name: "Mélange 5 baies")
Ingredient.create(name: "Mélange 5 épices")
Ingredient.create(name: "Mélange 5 parfums")
Ingredient.create(name: "Mélange d'épice 5 parfums")
Ingredient.create(name: "Mélange d'épice indienne")
Ingredient.create(name: "Mélange d'épice massala")
Ingredient.create(name: "Mélange d'épice mexicaine")
Ingredient.create(name: "Mélange d'épice orientale")
Ingredient.create(name: "Mélange d'épice pour chili")
Ingredient.create(name: "Mélange d'herbe pour poisson")
Ingredient.create(name: "Mélange poivre 5 baies")
Ingredient.create(name: "Mélasse")
Ingredient.create(name: "Melfor")
Ingredient.create(name: "Mélisse")
Ingredient.create(name: "Melloukhia")
Ingredient.create(name: "Melon")
Ingredient.create(name: "Melon d'eau")
Ingredient.create(name: "Melonade")
Ingredient.create(name: "Merguez")
Ingredient.create(name: "Meringue")
Ingredient.create(name: "Merlan")
Ingredient.create(name: "Merlu")
Ingredient.create(name: "Merluchon")
Ingredient.create(name: "Mérou")
Ingredient.create(name: "Mesclun")
Ingredient.create(name: "Metton")
Ingredient.create(name: "Michoko")
Ingredient.create(name: "Miel")
Ingredient.create(name: "Miel au romarin")
Ingredient.create(name: "Miel d'acacia")
Ingredient.create(name: "Miel liquide")
Ingredient.create(name: "Miette de crabe")
Ingredient.create(name: "Mikado")
Ingredient.create(name: "Millet")
Ingredient.create(name: "Mimolette")
Ingredient.create(name: "Mincemeat")
Ingredient.create(name: "Mini mais")
Ingredient.create(name: "Mini roulé")
Ingredient.create(name: "Mini smarties")
Ingredient.create(name: "Mirabelle")
Ingredient.create(name: "Mirin")
Ingredient.create(name: "Miso")
Ingredient.create(name: "Mizithra")
Ingredient.create(name: "Mloukhia")
Ingredient.create(name: "Moelle")
Ingredient.create(name: "Moelle de boeuf")
Ingredient.create(name: "Mogette")
Ingredient.create(name: "Molokheya")
Ingredient.create(name: "Monbazillac")
Ingredient.create(name: "Mont d'or")
Ingredient.create(name: "Montepulciano")
Ingredient.create(name: "Monterey jack")
Ingredient.create(name: "Morbier")
Ingredient.create(name: "Morille")
Ingredient.create(name: "Mortadelle")
Ingredient.create(name: "Morue")
Ingredient.create(name: "Moscatel")
Ingredient.create(name: "Moules")
Ingredient.create(name: "Mouloukhia")
Ingredient.create(name: "Mousse au chocolat")
Ingredient.create(name: "Mousse de foie")
Ingredient.create(name: "Mousseron")
Ingredient.create(name: "Mousseux")
Ingredient.create(name: "Moutarde")
Ingredient.create(name: "Moutarde à l'ancienne")
Ingredient.create(name: "Moutarde à l'estragon")
Ingredient.create(name: "Moutarde au poivre vert")
Ingredient.create(name: "Moutarde de dijon")
Ingredient.create(name: "Moutarde de meaux")
Ingredient.create(name: "Mouton")
Ingredient.create(name: "Mouzillon")
Ingredient.create(name: "Mozzarella")
Ingredient.create(name: "Mozzarella di buffala")
Ingredient.create(name: "Muesli")
Ingredient.create(name: "Muffin")
Ingredient.create(name: "Muffin complet")
Ingredient.create(name: "Mulet")
Ingredient.create(name: "Munster")
Ingredient.create(name: "Mûre")
Ingredient.create(name: "Murène")
Ingredient.create(name: "Musc")
Ingredient.create(name: "Muscade")
Ingredient.create(name: "Muscade rapée")
Ingredient.create(name: "Muscadet")
Ingredient.create(name: "Muscat")
Ingredient.create(name: "Muscovado")
Ingredient.create(name: "Museau")
Ingredient.create(name: "Myrtille")
Ingredient.create(name: "Nappage")
Ingredient.create(name: "Nappage chocolat")
Ingredient.create(name: "Nashi")
Ingredient.create(name: "Navarin d'agneau")
Ingredient.create(name: "Naveline (choucroute de navets)")
Ingredient.create(name: "Navet")
Ingredient.create(name: "Navette")
Ingredient.create(name: "Nectarine")
Ingredient.create(name: "Nèfle")
Ingredient.create(name: "Nem")
Ingredient.create(name: "Nesquik")
Ingredient.create(name: "Neufchâtel")
Ingredient.create(name: "Niébé")
Ingredient.create(name: "Noilly prat")
Ingredient.create(name: "Noisette")
Ingredient.create(name: "Noisette d'agneau")
Ingredient.create(name: "Noix")
Ingredient.create(name: "Noix de cajou")
Ingredient.create(name: "Noix de coco")
Ingredient.create(name: "Noix de coco rapée")
Ingredient.create(name: "Noix de grenoble")
Ingredient.create(name: "Noix de macadamia")
Ingredient.create(name: "Noix de pécan")
Ingredient.create(name: "Noix de saint-jacques")
Ingredient.create(name: "Noix vertes")
Ingredient.create(name: "Nopal")
Ingredient.create(name: "Nori")
Ingredient.create(name: "Nougat")
Ingredient.create(name: "Nougatine")
Ingredient.create(name: "Nouilles")
Ingredient.create(name: "Nouilles aux oeufs")
Ingredient.create(name: "Nouilles chinoises")
Ingredient.create(name: "Nouilles de riz")
Ingredient.create(name: "Nouilles soba")
Ingredient.create(name: "Nouilles udon")
Ingredient.create(name: "Nugget")
Ingredient.create(name: "Nuoc mam")
Ingredient.create(name: "Nutella")
Ingredient.create(name: "Oeillet")
Ingredient.create(name: "Oeuf")
Ingredient.create(name: "Oeuf de caille")
Ingredient.create(name: "Oeuf de lump")
Ingredient.create(name: "Oeuf d'oie")
Ingredient.create(name: "Oeufs de saumon")
Ingredient.create(name: "Oie")
Ingredient.create(name: "Oignon")
Ingredient.create(name: "Oignon au vinaigre")
Ingredient.create(name: "Oignon blanc")
Ingredient.create(name: "Oignon frit séché")
Ingredient.create(name: "Oignon grelot")
Ingredient.create(name: "Oignon jaune")
Ingredient.create(name: "Oignon nouveau")
Ingredient.create(name: "Oignon rose")
Ingredient.create(name: "Oignon rouge")
Ingredient.create(name: "Oiseau sans tête")
Ingredient.create(name: "Oka")
Ingredient.create(name: "Olive noire")
Ingredient.create(name: "Olive verte")
Ingredient.create(name: "Olives")
Ingredient.create(name: "Omble chevalier")
Ingredient.create(name: "Onglet")
Ingredient.create(name: "Orange")
Ingredient.create(name: "Orange amère")
Ingredient.create(name: "Orangeade")
Ingredient.create(name: "Orangeat")
Ingredient.create(name: "Orangette")
Ingredient.create(name: "Orangina")
Ingredient.create(name: "Orecchiette")
Ingredient.create(name: "Oreilles")
Ingredient.create(name: "Oréo")
Ingredient.create(name: "Orge")
Ingredient.create(name: "Origan")
Ingredient.create(name: "Ormeau")
Ingredient.create(name: "Oronge")
Ingredient.create(name: "Orphie")
Ingredient.create(name: "Ortie")
Ingredient.create(name: "Os à moelle")
Ingredient.create(name: "Oseille")
Ingredient.create(name: "Ossau iraty")
Ingredient.create(name: "Ouassou")
Ingredient.create(name: "Oursin")
Ingredient.create(name: "Ourson en guimauve")
Ingredient.create(name: "Ouzo")
Ingredient.create(name: "Pageot")
Ingredient.create(name: "Paille d'Or")
Ingredient.create(name: "Pain")
Ingredient.create(name: "Pain au figue")
Ingredient.create(name: "Pain au lait")
Ingredient.create(name: "Pain au olive")
Ingredient.create(name: "Pain aux céréales")
Ingredient.create(name: "Pain brioché")
Ingredient.create(name: "Pain bruschelle")
Ingredient.create(name: "Pain complet")
Ingredient.create(name: "Pain de campagne")
Ingredient.create(name: "Pain de mie")
Ingredient.create(name: "Pain de seigle")
Ingredient.create(name: "Pain d'épice")
Ingredient.create(name: "Pain indien naan")
Ingredient.create(name: "Pain pita")
Ingredient.create(name: "Pain polka")
Ingredient.create(name: "Pain pour hamburger")
Ingredient.create(name: "Pain viennois")
Ingredient.create(name: "Pak choi")
Ingredient.create(name: "Paleron")
Ingredient.create(name: "Palet moelleux")
Ingredient.create(name: "Palets bretons")
Ingredient.create(name: "Palets coco")
Ingredient.create(name: "Palette")
Ingredient.create(name: "Palombe")
Ingredient.create(name: "Palourde")
Ingredient.create(name: "Pamplemousse")
Ingredient.create(name: "Panais")
Ingredient.create(name: "Pancake")
Ingredient.create(name: "Pancetta")
Ingredient.create(name: "Pandan")
Ingredient.create(name: "Pandoro")
Ingredient.create(name: "Panettone")
Ingredient.create(name: "Panga")
Ingredient.create(name: "Pangasius")
Ingredient.create(name: "Panne")
Ingredient.create(name: "Panse")
Ingredient.create(name: "Panse de brebis")
Ingredient.create(name: "Pansette")
Ingredient.create(name: "Panure")
Ingredient.create(name: "Papaye")
Ingredient.create(name: "Papier azyme")
Ingredient.create(name: "Papier sulfurisé")
Ingredient.create(name: "Pappardelles")
Ingredient.create(name: "Paprika")
Ingredient.create(name: "Pariétaire")
Ingredient.create(name: "Parmesan")
Ingredient.create(name: "Parmesan râpé")
Ingredient.create(name: "Parpardelle")
Ingredient.create(name: "Passata")
Ingredient.create(name: "Passe-pierre")
Ingredient.create(name: "Passetougrain")
Ingredient.create(name: "Passoa")
Ingredient.create(name: "Pastèque")
Ingredient.create(name: "Pastis")
Ingredient.create(name: "Pastrami")
Ingredient.create(name: "Patate douce")
Ingredient.create(name: "Pâte")
Ingredient.create(name: "Pâté")
Ingredient.create(name: "Pâte à beignet")
Ingredient.create(name: "Pâte à brioche")
Ingredient.create(name: "Pâte à crêpe")
Ingredient.create(name: "Pâte à lasagne")
Ingredient.create(name: "Pâte à pain")
Ingredient.create(name: "Pâte à pizza")
Ingredient.create(name: "Pâte à raviolis")
Ingredient.create(name: "Pâte à sucre")
Ingredient.create(name: "Pâte à tartiner")
Ingredient.create(name: "Pâte brisée")
Ingredient.create(name: "Pâte d'amande")
Ingredient.create(name: "Pâte d'arachide")
Ingredient.create(name: "Pâté de campagne")
Ingredient.create(name: "Pâte de crevette")
Ingredient.create(name: "Pâte de curry")
Ingredient.create(name: "Pâté de foie")
Ingredient.create(name: "Pâte de pavot")
Ingredient.create(name: "Pâte de semoule de blé")
Ingredient.create(name: "Pâte de spéculoos")
Ingredient.create(name: "Pâte feuilletée")
Ingredient.create(name: "Pâte filo")
Ingredient.create(name: "Pâte grecque")
Ingredient.create(name: "Pâte sablée")
Ingredient.create(name: "Pâte torsade semi-complète")
Ingredient.create(name: "Pâtes")
Ingredient.create(name: "Pâtes à l'encre de seiche")
Ingredient.create(name: "Pâtes au quinoa")
Ingredient.create(name: "Pâtes fraîches")
Ingredient.create(name: "Pâtes tricolores")
Ingredient.create(name: "Patidou")
Ingredient.create(name: "Pâtisson")
Ingredient.create(name: "Patrelle")
Ingredient.create(name: "Paupiette")
Ingredient.create(name: "Pavot")
Ingredient.create(name: "Pêche")
Ingredient.create(name: "Pecorino")
Ingredient.create(name: "Pecorino pepato")
Ingredient.create(name: "Pecorino romano")
Ingredient.create(name: "Pectine")
Ingredient.create(name: "Peepermint")
Ingredient.create(name: "Pélardon")
Ingredient.create(name: "Penne")
Ingredient.create(name: "Pensée")
Ingredient.create(name: "Pèpè")
Ingredient.create(name: "Pepino")
Ingredient.create(name: "Pépite caramélisée")
Ingredient.create(name: "Pépite de nougatine")
Ingredient.create(name: "Pépite en chocolat")
Ingredient.create(name: "Perche")
Ingredient.create(name: "Perche du nil")
Ingredient.create(name: "Perdreau")
Ingredient.create(name: "Perdrix")
Ingredient.create(name: "Perle argentée")
Ingredient.create(name: "Perle du Japon")
Ingredient.create(name: "Perle multicolore")
Ingredient.create(name: "Perrier")
Ingredient.create(name: "Persil")
Ingredient.create(name: "Persillade")
Ingredient.create(name: "Pesto")
Ingredient.create(name: "Pesto rosso")
Ingredient.create(name: "Pétale de fleur")
Ingredient.create(name: "Petit beurre")
Ingredient.create(name: "Petit brun")
Ingredient.create(name: "Petit lu")
Ingredient.create(name: "Petit pain suédois")
Ingredient.create(name: "Petit piment")
Ingredient.create(name: "Petit pois")
Ingredient.create(name: "Petit salé")
Ingredient.create(name: "Petit suisse")
Ingredient.create(name: "Pétoncle")
Ingredient.create(name: "Philadelphia")
Ingredient.create(name: "Philadephia")
Ingredient.create(name: "Physalis")
Ingredient.create(name: "Piballe")
Ingredient.create(name: "Piccalilli")
Ingredient.create(name: "Pickle")
Ingredient.create(name: "Picodon")
Ingredient.create(name: "Picon")
Ingredient.create(name: "Pied de cochon")
Ingredient.create(name: "Pied-de-mouton")
Ingredient.create(name: "Pieds")
Ingredient.create(name: "Pieds de mouton")
Ingredient.create(name: "Pigeon")
Ingredient.create(name: "Pigeonneau")
Ingredient.create(name: "Pignon")
Ingredient.create(name: "Pili Pili")
Ingredient.create(name: "Pilon de poulet")
Ingredient.create(name: "Pil-pil")
Ingredient.create(name: "Piment")
Ingredient.create(name: "Piment chipotle")
Ingredient.create(name: "Piment de Cayenne")
Ingredient.create(name: "Piment d'espelette")
Ingredient.create(name: "Piment fort")
Ingredient.create(name: "Piment fort d'espelette")
Ingredient.create(name: "Piment vert")
Ingredient.create(name: "Pimiento del piquillo")
Ingredient.create(name: "Pimprenelle")
Ingredient.create(name: "Pineau blanc des Charentes")
Ingredient.create(name: "Pineau des charentes")
Ingredient.create(name: "Pinot blanc")
Ingredient.create(name: "Pinot noir")
Ingredient.create(name: "Pintade")
Ingredient.create(name: "Pintadeau")
Ingredient.create(name: "Pipe Rigate")
Ingredient.create(name: "Piperade")
Ingredient.create(name: "Piquillo")
Ingredient.create(name: "Pisang")
Ingredient.create(name: "Pisco")
Ingredient.create(name: "Pissenlit")
Ingredient.create(name: "Pistache")
Ingredient.create(name: "Pistou")
Ingredient.create(name: "Pitaya")
Ingredient.create(name: "Planta Fin Culinesse")
Ingredient.create(name: "Plantain")
Ingredient.create(name: "Plat de côte")
Ingredient.create(name: "Pleurote")
Ingredient.create(name: "Plie")
Ingredient.create(name: "Plum sauce")
Ingredient.create(name: "Pointe d'asperge")
Ingredient.create(name: "Pointe d'asperge verte")
Ingredient.create(name: "Poire")
Ingredient.create(name: "Poiré")
Ingredient.create(name: "Poireau")
Ingredient.create(name: "Pois")
Ingredient.create(name: "Pois cassés")
Ingredient.create(name: "Pois chiche")
Ingredient.create(name: "Pois écossés")
Ingredient.create(name: "Pois gourmand")
Ingredient.create(name: "Pois mange-tout")
Ingredient.create(name: "Poitrine d'agneau")
Ingredient.create(name: "Poitrine de porc")
Ingredient.create(name: "Poitrine fumée")
Ingredient.create(name: "Poivrade")
Ingredient.create(name: "Poivre")
Ingredient.create(name: "Poivre 5 baies")
Ingredient.create(name: "Poivre au citron")
Ingredient.create(name: "Poivre blanc")
Ingredient.create(name: "Poivre cubèbe")
Ingredient.create(name: "Poivre de cayenne")
Ingredient.create(name: "Poivre de sichuan")
Ingredient.create(name: "Poivre en grain")
Ingredient.create(name: "Poivre long")
Ingredient.create(name: "Poivre vert")
Ingredient.create(name: "Poivron")
Ingredient.create(name: "Poivron rouge")
Ingredient.create(name: "Polenta")
Ingredient.create(name: "Pomélo")
Ingredient.create(name: "Pomelo chinois")
Ingredient.create(name: "Pomme")
Ingredient.create(name: "Pomme de terre")
Ingredient.create(name: "Pomme de terre rouge")
Ingredient.create(name: "Pommeau")
Ingredient.create(name: "Pommette")
Ingredient.create(name: "Pont l'évêque")
Ingredient.create(name: "Pop corn")
Ingredient.create(name: "Porc")
Ingredient.create(name: "Porcelet")
Ingredient.create(name: "Porto")
Ingredient.create(name: "Port-salut")
Ingredient.create(name: "Potatoe")
Ingredient.create(name: "Pot-au-feu")
Ingredient.create(name: "Potimarron")
Ingredient.create(name: "Potiron")
Ingredient.create(name: "Poudre à chili")
Ingredient.create(name: "Poudre à colombo")
Ingredient.create(name: "Poudre à flan")
Ingredient.create(name: "Poudre à lever")
Ingredient.create(name: "Poudre d'amande")
Ingredient.create(name: "Poudre de coco")
Ingredient.create(name: "Poudre de colombo")
Ingredient.create(name: "Poudre de noisette")
Ingredient.create(name: "Poudre de piment de cayenne")
Ingredient.create(name: "Poudre de pudding")
Ingredient.create(name: "Poularde")
Ingredient.create(name: "Poule")
Ingredient.create(name: "Poulet")
Ingredient.create(name: "Poulet entier")
Ingredient.create(name: "Poulpe")
Ingredient.create(name: "Poumons")
Ingredient.create(name: "Pourpier")
Ingredient.create(name: "Pousse de bambou")
Ingredient.create(name: "Pousse de lotus")
Ingredient.create(name: "Pousse d'épinard")
Ingredient.create(name: "Pousse-Rapière")
Ingredient.create(name: "Poussin")
Ingredient.create(name: "Poutargue")
Ingredient.create(name: "Praire")
Ingredient.create(name: "Pralin")
Ingredient.create(name: "Praline")
Ingredient.create(name: "Praliné")
Ingredient.create(name: "Praline rouge")
Ingredient.create(name: "Pralinoise")
Ingredient.create(name: "Préparation pour flan nature")
Ingredient.create(name: "Présure")
Ingredient.create(name: "Prosciutto")
Ingredient.create(name: "Prosecco")
Ingredient.create(name: "Protéine de soja")
Ingredient.create(name: "Provolone")
Ingredient.create(name: "Prune")
Ingredient.create(name: "Pruneaux")
Ingredient.create(name: "Prunelle")
Ingredient.create(name: "Pulpe de tomate")
Ingredient.create(name: "Punch coco")
Ingredient.create(name: "Purée")
Ingredient.create(name: "Purée d'aubergine")
Ingredient.create(name: "Purée de carotte")
Ingredient.create(name: "Purée de marron")
Ingredient.create(name: "Purée de piment")
Ingredient.create(name: "Purée d'épinard")
Ingredient.create(name: "Purée d'oignon")
Ingredient.create(name: "Quatre-épices")
Ingredient.create(name: "Quatre-quart")
Ingredient.create(name: "Quatre-quarts")
Ingredient.create(name: "Quenelle")
Ingredient.create(name: "Quenelle de veau")
Ingredient.create(name: "Quetsche")
Ingredient.create(name: "Queue")
Ingredient.create(name: "Queue de langouste")
Ingredient.create(name: "Queue d'écrevisse")
Ingredient.create(name: "Quinoa")
Ingredient.create(name: "Quinquina")
Ingredient.create(name: "Quorn")
Ingredient.create(name: "Râble de lapin")
Ingredient.create(name: "Râble de lièvre")
Ingredient.create(name: "Racine de gentiane")
Ingredient.create(name: "Raclette")
Ingredient.create(name: "Radis")
Ingredient.create(name: "Raffaelo")
Ingredient.create(name: "Ragondin")
Ingredient.create(name: "Raie")
Ingredient.create(name: "Raifort")
Ingredient.create(name: "Raisin")
Ingredient.create(name: "Raisin blanc")
Ingredient.create(name: "Raisin muscat")
Ingredient.create(name: "Raisin noir")
Ingredient.create(name: "Raisiné")
Ingredient.create(name: "Raisins secs")
Ingredient.create(name: "Rameau de fleur d'acacia")
Ingredient.create(name: "Ramen")
Ingredient.create(name: "Rapadura")
Ingredient.create(name: "Ras el Hanout")
Ingredient.create(name: "Rascalat")
Ingredient.create(name: "Rascasse")
Ingredient.create(name: "Ratafia")
Ingredient.create(name: "Ratatouille")
Ingredient.create(name: "Rate")
Ingredient.create(name: "Ratte")
Ingredient.create(name: "Rave")
Ingredient.create(name: "Raviole")
Ingredient.create(name: "Raviole de Royans")
Ingredient.create(name: "Ravioli")
Ingredient.create(name: "Reblochon")
Ingredient.create(name: "Réglisse")
Ingredient.create(name: "Reine-claude")
Ingredient.create(name: "Relish")
Ingredient.create(name: "Renne")
Ingredient.create(name: "Requin")
Ingredient.create(name: "Rhubarbe")
Ingredient.create(name: "Rhum")
Ingredient.create(name: "Rhum vieux")
Ingredient.create(name: "Rice crispies")
Ingredient.create(name: "Ricoré")
Ingredient.create(name: "Ricotta")
Ingredient.create(name: "Riesling")
Ingredient.create(name: "Rigatoni")
Ingredient.create(name: "Rillettes")
Ingredient.create(name: "Rillons")
Ingredient.create(name: "Ris de veau")
Ingredient.create(name: "Risotto")
Ingredient.create(name: "Riz")
Ingredient.create(name: "Riz basmati")
Ingredient.create(name: "Riz blanc")
Ingredient.create(name: "Riz gluant")
Ingredient.create(name: "Riz long")
Ingredient.create(name: "Riz pour risotto")
Ingredient.create(name: "Riz rond")
Ingredient.create(name: "Riz sauvage")
Ingredient.create(name: "Riz surinam")
Ingredient.create(name: "Riz thaï")
Ingredient.create(name: "Rocamadour")
Ingredient.create(name: "Rognons")
Ingredient.create(name: "Romaine")
Ingredient.create(name: "Romarin")
Ingredient.create(name: "Roquefort")
Ingredient.create(name: "Roquette")
Ingredient.create(name: "Rosbif")
Ingredient.create(name: "Rose")
Ingredient.create(name: "Rosette")
Ingredient.create(name: "Rösti")
Ingredient.create(name: "Rôti de biche")
Ingredient.create(name: "Roti de boeuf")
Ingredient.create(name: "Rôti de dindonneau")
Ingredient.create(name: "Roti de porc")
Ingredient.create(name: "Rôti de veau")
Ingredient.create(name: "Roucaou")
Ingredient.create(name: "Roudor")
Ingredient.create(name: "Rouget")
Ingredient.create(name: "Rouille")
Ingredient.create(name: "Rouy")
Ingredient.create(name: "Rue")
Ingredient.create(name: "Rumsteak")
Ingredient.create(name: "Rumsteck")
Ingredient.create(name: "Rutabaga")
Ingredient.create(name: "Sablés")
Ingredient.create(name: "Sabodet")
Ingredient.create(name: "Sabre")
Ingredient.create(name: "Safran")
Ingredient.create(name: "Saindoux")
Ingredient.create(name: "Saint Agur")
Ingredient.create(name: "Saint Morêt")
Ingredient.create(name: "Sainte-maure de Touraine")
Ingredient.create(name: "Saint-felicien")
Ingredient.create(name: "Saint-florentin")
Ingredient.create(name: "Saint-marcellin")
Ingredient.create(name: "Saint-nectaire")
Ingredient.create(name: "Saint-paulin")
Ingredient.create(name: "Saint-pierre")
Ingredient.create(name: "Saka-Saka")
Ingredient.create(name: "Saké")
Ingredient.create(name: "Salade")
Ingredient.create(name: "Salade mélangée")
Ingredient.create(name: "Salami")
Ingredient.create(name: "Salers")
Ingredient.create(name: "Salicorne")
Ingredient.create(name: "Salpêtre")
Ingredient.create(name: "Salsifi")
Ingredient.create(name: "Sambal Oelek")
Ingredient.create(name: "Sancerre")
Ingredient.create(name: "Sandre")
Ingredient.create(name: "Sang")
Ingredient.create(name: "Sanglier")
Ingredient.create(name: "Sangria")
Ingredient.create(name: "Sanguin")
Ingredient.create(name: "Sar")
Ingredient.create(name: "Sardine")
Ingredient.create(name: "Sarrasin")
Ingredient.create(name: "Sarriette")
Ingredient.create(name: "Satay")
Ingredient.create(name: "Saté")
Ingredient.create(name: "Sauce soja-sésame")
Ingredient.create(name: "Sauce à l'oseille")
Ingredient.create(name: "Sauce à tacos")
Ingredient.create(name: "Sauce aigre douce")
Ingredient.create(name: "Sauce américaine")
Ingredient.create(name: "Sauce anglaise")
Ingredient.create(name: "Sauce armoricaine")
Ingredient.create(name: "Sauce Arrabiata")
Ingredient.create(name: "Sauce asiatique")
Ingredient.create(name: "Sauce au gingembre")
Ingredient.create(name: "Sauce au poivre")
Ingredient.create(name: "Sauce barbecue")
Ingredient.create(name: "Sauce béarnaise")
Ingredient.create(name: "Sauce blanche")
Ingredient.create(name: "Sauce bolognaise")
Ingredient.create(name: "Sauce bourguignonne")
Ingredient.create(name: "Sauce brune")
Ingredient.create(name: "Sauce burger")
Ingredient.create(name: "Sauce caramel")
Ingredient.create(name: "Sauce chocolat")
Ingredient.create(name: "Sauce cocktail")
Ingredient.create(name: "Sauce crudité")
Ingredient.create(name: "Sauce de rôti")
Ingredient.create(name: "Sauce demi-glace")
Ingredient.create(name: "Sauce d'huître")
Ingredient.create(name: "Sauce forestière")
Ingredient.create(name: "Sauce hamburger")
Ingredient.create(name: "Sauce hannibal")
Ingredient.create(name: "Sauce harissa")
Ingredient.create(name: "Sauce hoisin")
Ingredient.create(name: "Sauce hollandaise")
Ingredient.create(name: "Sauce HP")
Ingredient.create(name: "Sauce huître")
Ingredient.create(name: "Sauce italienne")
Ingredient.create(name: "Sauce ketchup")
Ingredient.create(name: "Sauce maggi")
Ingredient.create(name: "Sauce napolitaine")
Ingredient.create(name: "Sauce nuoc mam")
Ingredient.create(name: "Sauce pimentée")
Ingredient.create(name: "Sauce piquante")
Ingredient.create(name: "Sauce pistou")
Ingredient.create(name: "Sauce pizza")
Ingredient.create(name: "Sauce pour nem")
Ingredient.create(name: "Sauce pour wok au curry doux")
Ingredient.create(name: "Sauce provençale")
Ingredient.create(name: "Sauce salsa")
Ingredient.create(name: "Sauce satay")
Ingredient.create(name: "Sauce sichuan")
Ingredient.create(name: "Sauce soja")
Ingredient.create(name: "Sauce Sriracha")
Ingredient.create(name: "Sauce sukiyaki")
Ingredient.create(name: "Sauce sweet chili")
Ingredient.create(name: "Sauce tamari")
Ingredient.create(name: "Sauce tartare")
Ingredient.create(name: "Sauce Tempura")
Ingredient.create(name: "Sauce teriyaki")
Ingredient.create(name: "Sauce thaï")
Ingredient.create(name: "Sauce tomate")
Ingredient.create(name: "Sauce Worcester")
Ingredient.create(name: "Sauce worcestershire")
Ingredient.create(name: "Sauce Yakitori")
Ingredient.create(name: "Sauceline")
Ingredient.create(name: "Saucisse cocktail")
Ingredient.create(name: "Saucisse de Francfort")
Ingredient.create(name: "Saucisse de Montbéliard")
Ingredient.create(name: "Saucisse de morteau")
Ingredient.create(name: "Saucisse de Strasboug")
Ingredient.create(name: "Saucisse de Toulouse")
Ingredient.create(name: "Saucisse sèche")
Ingredient.create(name: "Saucisses")
Ingredient.create(name: "Saucisson")
Ingredient.create(name: "Saucisson à l'ail")
Ingredient.create(name: "Saucisson sec")
Ingredient.create(name: "Sauge")
Ingredient.create(name: "Saumon")
Ingredient.create(name: "Saumon au naturel")
Ingredient.create(name: "Saumon frais")
Ingredient.create(name: "Saumon fumé")
Ingredient.create(name: "Saumonette")
Ingredient.create(name: "Saurel")
Ingredient.create(name: "Sauté")
Ingredient.create(name: "Sauté de porc")
Ingredient.create(name: "Sauterelle")
Ingredient.create(name: "Sauterne")
Ingredient.create(name: "Savora")
Ingredient.create(name: "Sbrinz")
Ingredient.create(name: "Scampi")
Ingredient.create(name: "Scarole")
Ingredient.create(name: "Schnaps")
Ingredient.create(name: "Schweppes")
Ingredient.create(name: "Scorsonère")
Ingredient.create(name: "Sébaste")
Ingredient.create(name: "Seiche")
Ingredient.create(name: "Seigle")
Ingredient.create(name: "Seitan")
Ingredient.create(name: "Sel")
Ingredient.create(name: "Sel au épice")
Ingredient.create(name: "Sel au herbe")
Ingredient.create(name: "Sel au piment d'espelette")
Ingredient.create(name: "Sel de céleri")
Ingredient.create(name: "Selle d'agneau")
Ingredient.create(name: "Semoule")
Ingredient.create(name: "Semoule fine")
Ingredient.create(name: "Semoule moyenne")
Ingredient.create(name: "Séré")
Ingredient.create(name: "Serpent")
Ingredient.create(name: "Serpolet")
Ingredient.create(name: "Serran")
Ingredient.create(name: "Sésame")
Ingredient.create(name: "Seven Up")
Ingredient.create(name: "Sévereau")
Ingredient.create(name: "Sherry")
Ingredient.create(name: "Shichimi togarashi")
Ingredient.create(name: "Shii také")
Ingredient.create(name: "Siave")
Ingredient.create(name: "Silure")
Ingredient.create(name: "Sirop")
Ingredient.create(name: "Sirop à l'aspérule")
Ingredient.create(name: "Sirop au fruit exotique")
Ingredient.create(name: "Sirop d'agave")
Ingredient.create(name: "Sirop d'ananas")
Ingredient.create(name: "Sirop de canne")
Ingredient.create(name: "Sirop de curaçao")
Ingredient.create(name: "Sirop de génépi")
Ingredient.create(name: "Sirop de Liège")
Ingredient.create(name: "Sirop de violette")
Ingredient.create(name: "Sirop d'érable")
Ingredient.create(name: "Sirop d'orange")
Ingredient.create(name: "Sirop d'orgeat")
Ingredient.create(name: "Smartie")
Ingredient.create(name: "Smoothie")
Ingredient.create(name: "Snickers")
Ingredient.create(name: "Soda")
Ingredient.create(name: "Soho")
Ingredient.create(name: "Soja")
Ingredient.create(name: "Soju")
Ingredient.create(name: "Sole")
Ingredient.create(name: "Sole portion")
Ingredient.create(name: "Son de blé")
Ingredient.create(name: "Sorbet ananas")
Ingredient.create(name: "Sorbet au citron vert")
Ingredient.create(name: "Sorbet citron")
Ingredient.create(name: "Sorbet citron vert")
Ingredient.create(name: "Sorbet coco")
Ingredient.create(name: "Sorbet melon")
Ingredient.create(name: "Sorbet mirabelle")
Ingredient.create(name: "Sorbet pomme verte")
Ingredient.create(name: "Sot-l'y-laisse")
Ingredient.create(name: "Soubressade")
Ingredient.create(name: "Soucis")
Ingredient.create(name: "Soupe oxtail")
Ingredient.create(name: "Souris d'agneau")
Ingredient.create(name: "Souris de boeuf")
Ingredient.create(name: "Spaghetti")
Ingredient.create(name: "Spaghettini")
Ingredient.create(name: "Spätzle")
Ingredient.create(name: "Speck")
Ingredient.create(name: "Spéculoos")
Ingredient.create(name: "Spigol")
Ingredient.create(name: "Spiruline")
Ingredient.create(name: "Sprat")
Ingredient.create(name: "Steak")
Ingredient.create(name: "Steak haché")
Ingredient.create(name: "Stévia")
Ingredient.create(name: "Stilton")
Ingredient.create(name: "Stollen")
Ingredient.create(name: "Stylo pâtissier")
Ingredient.create(name: "Sucre")
Ingredient.create(name: "Sucre candi")
Ingredient.create(name: "Sucre de canne")
Ingredient.create(name: "Sucre en grain")
Ingredient.create(name: "Sucre en morceaux")
Ingredient.create(name: "Sucre en poudre")
Ingredient.create(name: "Sucre fin")
Ingredient.create(name: "Sucre glace")
Ingredient.create(name: "Sucre roux")
Ingredient.create(name: "Sucre semoule")
Ingredient.create(name: "Sucre vanillé")
Ingredient.create(name: "Sucre vanilliné")
Ingredient.create(name: "Sucrette")
Ingredient.create(name: "Sucrine")
Ingredient.create(name: "Sujet en chocolat")
Ingredient.create(name: "Sumac")
Ingredient.create(name: "Surimi")
Ingredient.create(name: "Sylvaner")
Ingredient.create(name: "Tabasco")
Ingredient.create(name: "Taboulé")
Ingredient.create(name: "Tacaud")
Ingredient.create(name: "Tacos")
Ingredient.create(name: "Tagliatelle")
Ingredient.create(name: "Tagliatelle fraîche")
Ingredient.create(name: "Tahin")
Ingredient.create(name: "Tahiné")
Ingredient.create(name: "Takuan")
Ingredient.create(name: "Taleggio")
Ingredient.create(name: "Tamari")
Ingredient.create(name: "Tamarin")
Ingredient.create(name: "Tanche")
Ingredient.create(name: "Tandoori")
Ingredient.create(name: "Tapenade")
Ingredient.create(name: "Tapenade noire")
Ingredient.create(name: "Tapenade verte")
Ingredient.create(name: "Tapioca")
Ingredient.create(name: "Tarama")
Ingredient.create(name: "Tartare d'algue")
Ingredient.create(name: "Tartufata")
Ingredient.create(name: "Taureau")
Ingredient.create(name: "Tellines")
Ingredient.create(name: "Tende de tranche")
Ingredient.create(name: "Téquila")
Ingredient.create(name: "Tête de cochon")
Ingredient.create(name: "Tête de veau")
Ingredient.create(name: "Tétine")
Ingredient.create(name: "Tétragone")
Ingredient.create(name: "Thé")
Ingredient.create(name: "Thé aromatisé")
Ingredient.create(name: "Thé matcha")
Ingredient.create(name: "Thé vert")
Ingredient.create(name: "Thiof")
Ingredient.create(name: "Thon")
Ingredient.create(name: "Thon blanc")
Ingredient.create(name: "Thon rouge")
Ingredient.create(name: "Thym")
Ingredient.create(name: "Thym citron")
Ingredient.create(name: "Tilapia")
Ingredient.create(name: "Tilleul")
Ingredient.create(name: "Tilsit")
Ingredient.create(name: "Toast")
Ingredient.create(name: "Toastinette")
Ingredient.create(name: "Toblerone")
Ingredient.create(name: "Tofu")
Ingredient.create(name: "Tofu soyeux")
Ingredient.create(name: "Tokay")
Ingredient.create(name: "Tomate")
Ingredient.create(name: "Tomate cerise")
Ingredient.create(name: "Tomate concassée")
Ingredient.create(name: "Tomate pelée")
Ingredient.create(name: "Tomate séchée")
Ingredient.create(name: "Tomate séchée à l'huile d'olive")
Ingredient.create(name: "Tomate verte")
Ingredient.create(name: "Tomme")
Ingredient.create(name: "Tomme vaudoise")
Ingredient.create(name: "Tonic")
Ingredient.create(name: "Tonka (fève)")
Ingredient.create(name: "Topinambour")
Ingredient.create(name: "Torsades")
Ingredient.create(name: "Torsette")
Ingredient.create(name: "Tortellini")
Ingredient.create(name: "Tortilla")
Ingredient.create(name: "Tortilla chips")
Ingredient.create(name: "Tournedos")
Ingredient.create(name: "Tourteau")
Ingredient.create(name: "Travers de porc")
Ingredient.create(name: "Trévise")
Ingredient.create(name: "Tripes")
Ingredient.create(name: "Triple sec")
Ingredient.create(name: "Trompette de la mort")
Ingredient.create(name: "Truffe")
Ingredient.create(name: "Truffe blanche d'alba")
Ingredient.create(name: "Truffe noire de bourgogne")
Ingredient.create(name: "Truite")
Ingredient.create(name: "Truite saumonée")
Ingredient.create(name: "Tuc")
Ingredient.create(name: "Tuile au amande")
Ingredient.create(name: "Turbot")
Ingredient.create(name: "Turron")
Ingredient.create(name: "Tzatziki")
Ingredient.create(name: "Vache qui rit")
Ingredient.create(name: "Vacherin")
Ingredient.create(name: "Vanille")
Ingredient.create(name: "Vanilline")
Ingredient.create(name: "Veau")
Ingredient.create(name: "Végétaline")
Ingredient.create(name: "Ventrèche")
Ingredient.create(name: "Vénus")
Ingredient.create(name: "Vergeoise")
Ingredient.create(name: "Vergeoise blonde")
Ingredient.create(name: "Vergeoise brune")
Ingredient.create(name: "Vermicelle en chocolat")
Ingredient.create(name: "Vermicelles")
Ingredient.create(name: "Vermicelles de riz")
Ingredient.create(name: "Vermicelles de soja")
Ingredient.create(name: "Vermouth")
Ingredient.create(name: "Verveine")
Ingredient.create(name: "Vet-tsin")
Ingredient.create(name: "Viande d’agneau")
Ingredient.create(name: "Viande d'autruche")
Ingredient.create(name: "Viande de grison")
Ingredient.create(name: "Viandox")
Ingredient.create(name: "Vieille")
Ingredient.create(name: "Vieux lille")
Ingredient.create(name: "Vieux pané")
Ingredient.create(name: "Vin blanc")
Ingredient.create(name: "Vin blanc sec")
Ingredient.create(name: "Vin rosé")
Ingredient.create(name: "Vin rouge")
Ingredient.create(name: "Vinaigre")
Ingredient.create(name: "Vinaigre aromatisé")
Ingredient.create(name: "Vinaigre aromatisé aux noix")
Ingredient.create(name: "Vinaigre balsamique")
Ingredient.create(name: "Vinaigre balsamique de figue")
Ingredient.create(name: "Vinaigre d'alcool")
Ingredient.create(name: "Vinaigre de cidre")
Ingredient.create(name: "Vinaigre de datte")
Ingredient.create(name: "Vinaigre de framboise")
Ingredient.create(name: "Vinaigre de riz")
Ingredient.create(name: "Vinaigre de vin")
Ingredient.create(name: "Vinaigre de xeres")
Ingredient.create(name: "Vinaigrette")
Ingredient.create(name: "Vinaigrette aux framboises")
Ingredient.create(name: "Violette")
Ingredient.create(name: "Violette au sucre")
Ingredient.create(name: "Vitpris")
Ingredient.create(name: "Vive")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Vol-au-vent")
Ingredient.create(name: "Vouvray")
Ingredient.create(name: "Wakame")
Ingredient.create(name: "Wasa")
Ingredient.create(name: "Wasabi")
Ingredient.create(name: "Whisky")
Ingredient.create(name: "Wonton")
Ingredient.create(name: "Xérès")
Ingredient.create(name: "Yaourt à la grecque")
Ingredient.create(name: "Yaourt allégé")
Ingredient.create(name: "Yaourt aromatisé")
Ingredient.create(name: "Yaourt aux fruits")
Ingredient.create(name: "Yaourt brassé")
Ingredient.create(name: "Yaourt nature")
Ingredient.create(name: "Yaourts")
Ingredient.create(name: "Yet")
Ingredient.create(name: "Yuzu")

#Filled Country TABLE
Country.create(name: "Allemagne", description: "De nombreuses spécialités bien connues viennent d'Allemagne. Outre les excellentes saucisses de Franckfort qui font la base de nombreux plats, on trouve de célèbres pâtisseries comme le strudel, la forêt noire ou les spritz.")
Country.create(name: "Sénégal", description: "Goûtez aux saveurs du Sénégal en cuisinant à la maison de délicieuses recettes traditionnelles sénégalaises : poulet en yassa, tiéboudienne de poisson, mafé au poulet ou boeuf, cabri au combo et patate douce, jus ou gelée de bissap (hibiscus)...")
Country.create(name: "Maroc", description: "Laissez-vous envoûter par la cuisine marocaine traditionnelle. Savamment épicées, les recettes marocaines font voyager vos papilles au Maghreb le temps d'un repas. Tajine traditionnel, couscous royal, cornes de gazelle, bricks à la viande, salade d'orange à la cannelle...")
Country.create(name: "Cameroun", description: "es recettes de cuisine du Cameroun sont riches en saveurs et diversifiées car les combinaisons originales d'épices et de condiments donnent des résultats à la fois inattendus et merveilleux. Ces plats ne sont pas trop pimentés et conviennent aux palais les plus délicats.")
Country.create(name: "Côte d'ivoire", description: "La cuisine ivoirienne est très variée. Elle est issue des différents plats provenant de tous les groupes ethniques qui vivent dans le pays. Elle est en général très pimentée.")
Country.create(name: "France", description: "Si la cuisine française est si renommée à travers le monde, c'est grâce à son raffinement et à la variété de ses plats. Découvrez ou redécouvrez les recettes les plus populaires de notre gastronomie : pot au feu, blanquette, coq au vin...")
Country.create(name: "Espagne", description: "ui dit recette espagnole ne dit pas que tortilla ou paëlla, la preuve avec cette sélection de recettes de cuisine espagnole pour vivre au rythme de l'Espagne toute l'année durant. A vous la cuisine espagnole : tapas, gaspacho, paëlla... muy caliente")
Country.create(name: "Grèce", description: "Moussaka, tzatziki et tarama ; rien qu'à prononcer le nom de ces spécialités grecques, on se sent déjà en voyage. Alors n'hésitez pas à les cuisiner vous-même. ")
Country.create(name: "Angleterre", description: "Non, la cuisine anglaise ne se résume pas au gigot à la menthe aux petits pois, au fish and chips ou à la gelly... C'est au Royaume-Uni que nous devons les délicieuses pâtisseries comme le crumble, les scones, le cake ou les muffins.")
Country.create(name: "Argentine", description: "Direction l’Argentine, pays réputé pour sa viande, son vin mais aussi ses délicieuses empanadas, un incontournable de la cuisine argentine !")
Country.create(name: "Mexique", description: "Envie de manger mexicain ? Faites votre choix parmi notre sélection de recettes mexicaines faciles et rapides à réaliser. A l'apéritif, commencez par servir un onctueux guacamole à l'avocat, tabasco et citron vert que vous picorerez avec des tacos.")
Country.create(name: "Etats-Unis", description: "La cuisine américaine, variée et multiple, distingue quelques us et coutumes : le barbecue, le brunch et les gâteaux ! En voilà des spécificités américaines ! Hamburgers, ribs, entrecôtes, badigeonnés de marinade que l’on fait griller entre amis, en famille, entre voisins ...")
Country.create(name: "Chili", description: "Le Chili possède une riche gastronomie, avec de nombreuses spécialités nationales et régionales, depuis le choclo du Nord aux fruits de mer de Patagonie.")
Country.create(name: "Chine", description: "Evadez-vous en Chine le temps d'un repas en mitonnant à la maison l'une des nos recettes chinoises faciles. Riz cantonnais, rouleaux de printemps, pâtés impériaux, poulet au soja, porc au caramel, canard laqué ou encore nouilles sautées !")
Country.create(name: "Japon", description: "La cuisine nippone a beaucoup de succès dans le monde entier et cuisiner japonais n'a aujourd'hui plus rien d'insurmontable. Lancez-vous et préparez de savoureux sushis, sashimis, makis, ramens, bentos, teriyakis...")
Country.create(name: "Inde", description: "Partez en Inde le temps d'un repas en cuisinant à la maison de délicieuses recettes indiennes faciles. Naan au fromage, savoureux curry indien, poulet tandoori, korma, biryani, agneau tikka massala.... ")
Country.create(name: "Afghanistan", description: "Subtil mélange des cuisines de ses voisins, la Chine, l'Inde et l'Iran, avec peut-être quelques traces de la cuisine méditerranéenne importée par les armées d'Alexandre, telle est la cuisine afghane. Riche de toutes ces saveurs, de tous ces raffinements, elle est très variée.")
Country.create(name: "Australie", description: "L’Australie possède de nombreux plats typiques ! Parmi ses spécialités, connaissez-vous la gourmande pavlova, les délicieux lamingtons ou encore les fameux dampers et Anzac biscuits ?")
Country.create(name: "Italie", description: "Ensoleillée et authentique, la cuisine italienne est l'une des plus appréciées au monde. Invitez l'Italie à votre table en cuisinant nos recettes italiennes traditionnelles et faciles. Commencez votre repas avec de savoureux antipasti et bouchées siciliennes, telles la caponata ou les arancini.")
Country.create(name: "Luxembourg", description: "La cuisine luxembourgeoise est une cuisine simple et internationale. Elle combine la cordialité allemande et la finesse franco-belge. Parmi les mets régionaux, on trouve le carré de porc fumé aux larges haricots ou a la choucroute, le cochon de lait en gelée et le jambon d'Ardennes.")
Country.create(name: "Palaos", description: "La cuisine paluane est la cuisine traditionnelle des Palaos, un pays d'Océanie situé à l'extrême ouest des îles Carolines. Elle est beaucoup influencée par la cuisine philippine.")

#Filled Unity TABLE
Unity.create(name: "Kilogramme", symbole: "kg")
Unity.create(name: "Gramme", symbole: "g")
Unity.create(name: "Millilitre", symbole: "ml")
Unity.create(name: "Centilitre", symbole: "cl")
Unity.create(name: "Décalitre", symbole: "dl")
Unity.create(name: "Litre", symbole: "l")
Unity.create(name: "Tasse", symbole: "c")
Unity.create(name: "Cuillerée à soupe", symbole: "Tbs")
Unity.create(name: "Cuillerée à café", symbole: "tsp")

#Filled Category TABLE
Category.create(name: "Entrée")
Category.create(name: "Plat principal")
Category.create(name: "Dessert")
Category.create(name: "Accompagnement")
Category.create(name: "Apéritif")
Category.create(name: "Sauce")
Category.create(name: "Boisson")

#Filled Cost Table
Cost.create(cost_level: 1)
Cost.create(cost_level: 2)
Cost.create(cost_level: 3)

#Filled Difficulty Table
Difficulty.create(difficulty_level: 1)
Difficulty.create(difficulty_level: 2)
Difficulty.create(difficulty_level: 3)

# Riz cantonnais
Dish.create(name: "Riz cantonnais", cost_id: 1, difficulty_id: 1, bake_time: 15, preparation_time: 10, number_people: 4, category_id: 2, country_id: 13)
Recipe.create(dish_id: 1, description: "Quaedam non disiungitur fractis ambo filius post constaret ut et multorum suam Crateras mandatum mandatum nulla dilatata ad fractis in.")
IngredientRecipe.create(unity_id: 2, ingredient_id: 1647, recipe_id: 1, quantity: 240)
IngredientRecipe.create(unity_id: 2, ingredient_id: 539, recipe_id: 1, quantity: 240)
IngredientRecipe.create(unity_id: nil, ingredient_id: 949, recipe_id: 1, quantity: 2)
IngredientRecipe.create(unity_id: nil, ingredient_id: 1270, recipe_id: 1, quantity: 4)
IngredientRecipe.create(unity_id: 2, ingredient_id: 1440, recipe_id: 1, quantity: 100)
IngredientRecipe.create(unity_id: 2, ingredient_id: 1430, recipe_id: 1, quantity: nil)
IngredientRecipe.create(unity_id: 8, ingredient_id: 938, recipe_id: 1, quantity: 1)
IngredientRecipe.create(unity_id: 8, ingredient_id: 939, recipe_id: 1, quantity: 2)
IngredientRecipe.create(unity_id: nil, ingredient_id: 1808, recipe_id: 1, quantity: nil)
IngredientRecipe.create(unity_id: 2, ingredient_id: 1507, recipe_id: 1, quantity: nil)